import assert from 'node:assert/strict';
import {readFileSync,existsSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const R=process.env.PAR_ROOT;const tests=[];const test=(name,run)=>tests.push({id:'application.embedding.'+name,run});
const cp=v=>structuredClone(v),tick=()=>new Promise(r=>setImmediate(r));const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};};
let api,F;
async function fixture(experiment=true){
 const file=join(process.env.PAR_PRESENTER_BUILD||join(R,'product/wp11/lib'),'application-embedding.js');assert.ok(existsSync(file),'application embedding implementation missing');
 api=await import(pathToFileURL(file));F=JSON.parse(readFileSync(process.env.PAR_APPLICATION_FIXTURE,'utf8'));
 let record=null;const calls=[],writes=[];let closed=0;
 const store={async load(){return cp(record);},async save(v){writes.push('save');if(record)assert.deepEqual(record.original,v);else record={original:cp(v),dispatchAttempted:false};},async markDispatch(id){writes.push('marker');assert.equal(record.original.operationId,id);assert.equal(record.dispatchAttempted,false);record.dispatchAttempted=true;}};
 let observing=F.empty;
 const port={async request(op,args,signal){calls.push(op);assert.equal(signal.aborted,false);return cp(({observe:observing,prepare:F.prepared,dispatch:F.observed,inquire:F.inquired,retire:F.retired})[op]);},async close(){closed++;}};
 const e=new api.ApplicationEmbedding(F.context,store,F.targets,{localExperiment:experiment});
 return{e,store,port,calls,writes,get record(){return record;},get closed(){return closed;},observing(v){observing=v;},replaceRecord(v){record=cp(v);}};
}
async function attached(experiment=true){const x=await fixture(experiment);x.e.attach(F.context,x.port);return x;}
async function staged(){const x=await attached();await x.e.stage('6f'.repeat(16),0);await x.e.observe();return x;}
async function prepared(){const x=await staged();await x.e.prepare();return x;}
const fails=(fn,code)=>assert.rejects(fn,e=>e.code===code);
test('construct-attach-no-io',async()=>{const x=await attached();assert.deepEqual(x.calls,[]);assert.deepEqual(x.writes,[]);assert.equal(x.e.current.caller,'UNLOADED');await x.e.detach();});
test('store-required',async()=>{await fixture();assert.throws(()=>new api.ApplicationEmbedding(F.context,null,F.targets));});
test('immutable-targets',async()=>{const x=await fixture();const a=cp(F.targets);const e=new api.ApplicationEmbedding(F.context,x.store,a,{localExperiment:true});a[0]='0'.repeat(64);e.attach(F.context,x.port);await e.stage('6f'.repeat(16),0);assert.deepEqual(x.record.original.targets,F.targets);await e.detach();});
test('explicit-load-empty-is-not-error',async()=>{const x=await attached();await x.e.restore();assert.equal(x.e.current.caller,'EMPTY');assert.deepEqual(x.calls,[]);await x.e.detach();});
test('stage-persists-without-wire',async()=>{const x=await attached();await x.e.stage('6f'.repeat(16),0);assert.equal(x.record.original.operationId,'6f'.repeat(16));assert.deepEqual(x.calls,[]);assert.equal(x.e.current.caller,'SAVED');await x.e.detach();});
test('prepare-before-stage-denied',async()=>{const x=await attached();await x.e.observe();await fails(()=>x.e.prepare(),'CALLER_INTENT_REQUIRED');assert.deepEqual(x.writes,[]);await x.e.detach();});
test('stage-failure-preserves-original-and-sends-nothing',async()=>{const x=await attached();const save=x.store.save;x.store.save=async v=>{await save(v);throw Error('sensitive path');};await assert.rejects(x.e.stage('6f'.repeat(16),0));assert.equal(x.e.current.original.operationId,'6f'.repeat(16));assert.equal(x.e.current.caller,'UNCERTAIN');assert.deepEqual(x.calls,[]);assert.ok(!JSON.stringify(x.e.current).includes('sensitive'));await x.e.detach();});
test('new-id-does-not-replace-old-slot',async()=>{const x=await staged();await assert.rejects(x.e.stage('a'.repeat(32),0));assert.equal(x.record.original.operationId,'6f'.repeat(16));await x.e.detach();});
test('invalid-id-rejected-before-store',async()=>{const x=await attached();await assert.rejects(x.e.stage('bad',0));assert.equal(x.record,null);assert.deepEqual(x.writes,[]);await x.e.detach();});
test('wrong-target-refused-before-store',async()=>{const x=await fixture();const e=new api.ApplicationEmbedding(F.context,x.store,['0'.repeat(64)],{localExperiment:true});e.attach(F.context,x.port);await assert.rejects(e.stage('6f'.repeat(16),0));assert.equal(x.record,null);await e.detach();});
test('default-experiment-disabled',async()=>{const x=await attached(false);await fails(()=>x.e.stage('6f'.repeat(16),0),'APPLICATION_EXPERIMENT_REQUIRED');await x.e.observe();assert.equal(x.e.can('dispatch'),false);await x.e.detach();});
test('prepare-dispatch-separate-explicit-calls',async()=>{const x=await prepared();assert.deepEqual(x.calls,['observe','prepare']);await x.e.dispatch();assert.deepEqual(x.calls,['observe','prepare','dispatch']);assert.equal(x.record.dispatchAttempted,true);await x.e.detach();});
test('dispatch-does-not-repeat',async()=>{const x=await prepared();await x.e.dispatch();await assert.rejects(x.e.dispatch());assert.equal(x.calls.filter(v=>v==='dispatch').length,1);await x.e.detach();});
test('marker-before-send-and-detach',async()=>{const x=await prepared();const mark=x.store.markDispatch;x.store.markDispatch=async id=>{await mark(id);void x.e.detach();};await assert.rejects(x.e.dispatch());await x.e.detach();assert.equal(x.record.dispatchAttempted,true);assert.equal(x.calls.filter(v=>v==='dispatch').length,0);assert.equal(x.e.current.dispatchAttempted,true);});
test('detach-does-not-retire-or-delete',async()=>{const x=await prepared();const before=cp(x.record);await x.e.detach();assert.deepEqual(x.record,before);assert.equal(x.closed,1);assert.equal(x.e.current.lifecycle,'DETACHED');assert.equal(x.calls.includes('retire'),false);});
test('detach-idempotent',async()=>{const x=await attached();await Promise.all([x.e.detach(),x.e.detach(),x.e.detach()]);assert.equal(x.closed,1);});
test('new-attach-requires-explicit-observe',async()=>{const x=await prepared();await x.e.detach();x.e.attach(F.context,x.port);assert.equal(x.e.current.snapshot,null);await assert.rejects(x.e.prepare());await x.e.detach();});
test('changed-authority-rebind-denied',async()=>{const x=await attached();await x.e.detach();const c=cp(F.context);c.document.scope.controlHead='f'.repeat(64);assert.throws(()=>x.e.attach(c,x.port),/APPLICATION_CONTEXT_MISMATCH/);});
test('changed-generation-rebind-denied',async()=>{const x=await attached();await x.e.detach();const c=cp(F.context);c.document.connectionGeneration='10';assert.throws(()=>x.e.attach(c,x.port),/APPLICATION_CONTEXT_MISMATCH/);});
test('same-owner-new-stream-allowed',async()=>{const x=await attached();await x.e.detach();const c=cp(F.context);c.document.streamId='ab'.repeat(16);x.e.attach(c,x.port);assert.equal(x.e.current.lifecycle,'ATTACHED');await x.e.detach();});
test('second-live-attach-denied',async()=>{const x=await attached();assert.throws(()=>x.e.attach(F.context,x.port),/APPLICATION_CONNECTION_OWNED/);await x.e.detach();});
test('close-failure-retains-resource-and-blocks-attach',async()=>{const x=await attached();x.port.close=async()=>{throw Error('private');};await assert.rejects(x.e.detach());assert.equal(x.e.current.lifecycle,'CLEANUP_UNCONFIRMED');assert.throws(()=>x.e.attach(F.context,x.port));assert.equal(x.e.checkCleanup(),false);});
test('pending-store-blocks-new-attach',async()=>{const x=await attached();const d=defer(),entered=defer();const save=x.store.save;x.store.save=async v=>{entered.resolve();await d.promise;await save(v);};const p=x.e.stage('6f'.repeat(16),0);p.catch(()=>{});await entered.promise;await assert.rejects(x.e.detach());assert.throws(()=>x.e.attach(F.context,x.port));d.resolve();await assert.rejects(p);await tick();assert.equal(x.e.checkCleanup(),true);assert.equal(x.record.original.operationId,'6f'.repeat(16));});
test('old-response-after-detach-not-adopted',async()=>{const x=await attached();const d=defer();x.port.request=()=>d.promise;const p=x.e.observe();p.catch(()=>{});await tick();await assert.rejects(x.e.detach());d.resolve(cp(F.empty));await assert.rejects(p);await tick();assert.equal(x.e.checkCleanup(),true);assert.equal(x.e.current.snapshot,null);});
test('single-view-lease',async()=>{const x=await attached();const release=x.e.acquireView();assert.throws(()=>x.e.acquireView(),/APPLICATION_VIEW_OWNED/);release();const again=x.e.acquireView();again();await x.e.detach();});
test('restore-never-clears-known-marker',async()=>{const x=await prepared();await x.e.dispatch();await x.e.detach();x.replaceRecord({...x.record,dispatchAttempted:false});x.e.attach(F.context,x.port);await assert.rejects(x.e.restore());assert.equal(x.e.current.dispatchAttempted,true);await x.e.detach();});
test('restore-missing-known-record-is-uncertain',async()=>{const x=await staged();await x.e.detach();x.replaceRecord(null);x.e.attach(F.context,x.port);await assert.rejects(x.e.restore());assert.equal(x.e.current.original.operationId,'6f'.repeat(16));await x.e.detach();});
test('recovery-observe-inquire-no-dispatch',async()=>{const x=await prepared();await x.e.dispatch();await x.e.detach();const e=new api.ApplicationEmbedding(F.context,x.store,F.targets,{localExperiment:true});e.attach(F.context,x.port);await e.restore();const n=x.calls.length;await e.observe();await e.inquire();assert.deepEqual(x.calls.slice(n),['observe','inquire']);assert.equal(e.current.dispatchAttempted,true);assert.equal(e.can('dispatch'),false);await e.detach();});
test('inquiry-failure-reason-and-marker-retained',async()=>{const x=await prepared();await x.e.dispatch();x.port.request=async()=>{throw Object.assign(Error('private path'),{code:'PIN_UNCERTAIN'});};await assert.rejects(x.e.inquire());assert.equal(x.e.current.reason,'PIN_UNCERTAIN');assert.equal(x.e.current.dispatchAttempted,true);await x.e.detach();});
test('busy-denies-second-operation',async()=>{const x=await attached();const d=defer();x.port.request=()=>d.promise;const p=x.e.observe();await assert.rejects(x.e.restore());d.resolve(cp(F.empty));await p;await x.e.detach();});
class Element{constructor(doc,tag){this.ownerDocument=doc;this.tagName=tag;this.children=[];this.attrs={};this.dataset={};this._text='';this.value='';this.disabled=false;this.checked=false;}set textContent(v){this._text=v;this.children=[]}get textContent(){return this._text+this.children.map(x=>x.textContent).join('')}setAttribute(k,v){this.attrs[k]=v}append(...v){this.children.push(...v)}replaceChildren(...v){this._text='';this.children=v}addEventListener(k,f){(this.events??={})[k]=f}focus(){}setSelectionRange(a,b){this.selectionStart=a;this.selectionEnd=b}close(){this.open=false}showModal(){this.open=true}}
class Document{createElement(t){return new Element(this,t)}}
const find=(root,fn)=>fn(root)?root:root.children.map(x=>find(x,fn)).find(Boolean);
async function rendered(){const x=await attached(),d=new Document(),root=d.createElement('div');const {mountReference}=await import(pathToFileURL(join(process.env.PAR_PRESENTER_BUILD||join(R,'product/wp11/lib'),'renderer.js')));const {state}=await import('../wp11/support.mjs');const note=state();note.scope={appId:F.context.document.scope.appId,spaceId:F.context.document.scope.spaceId,documentId:F.context.document.scope.documentId};note.authority.controlHead=F.context.document.scope.controlHead;note.authority.epoch=F.context.document.scope.epoch;return{...x,get closed(){return x.closed;},get record(){return x.record;},root,note,mountReference};}
const action=(x,op)=>find(x.root,e=>e.dataset.applicationAction===op);
test('reference-opt-in-and-mount-no-io',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});assert.ok(action(x,'observe'));assert.deepEqual(x.calls,[]);assert.deepEqual(x.writes,[]);view.destroy();await view.applicationCleanup();});
test('reference-no-binding-no-panel',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note);assert.equal(action(x,'observe'),undefined);view.destroy();await x.e.detach();});
test('reference-scope-mismatch-before-dom-change',async()=>{const x=await rendered();x.note.scope.documentId='other';x.root.textContent='keep';assert.throws(()=>x.mountReference(x.root,x.note,{applicationEmbedding:x.e}),/APPLICATION_SCOPE_MISMATCH/);assert.equal(x.root.textContent,'keep');await x.e.detach();});
test('reference-stage-prepare-two-separate-actions',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});assert.equal(action(x,'prepare').disabled,true);const id=find(x.root,e=>e.dataset.applicationField==='operationId'),rev=find(x.root,e=>e.dataset.applicationField==='expectedRevision');id.value='6f'.repeat(16);rev.value='0';await action(x,'stage').onclick();assert.deepEqual(x.calls,[]);await action(x,'observe').onclick();await action(x,'prepare').onclick();assert.deepEqual(x.calls,['observe','prepare']);view.destroy();await view.applicationCleanup();});
test('reference-dispatch-needs-fresh-review',async()=>{const x=await rendered();await x.e.stage('6f'.repeat(16),0);await x.e.observe();await x.e.prepare();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});assert.equal(action(x,'dispatch').disabled,true);const box=find(x.root,e=>e.dataset.applicationField==='review');box.checked=true;box.onchange();assert.equal(action(x,'dispatch').disabled,false);await action(x,'dispatch').onclick();assert.equal(x.calls.filter(o=>o==='dispatch').length,1);assert.equal(box.checked,false);assert.equal(action(x,'dispatch').disabled,true);view.destroy();await view.applicationCleanup();});
test('reference-draft-ime-kept-through-status-change',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});const area=find(x.root,e=>e.dataset.test==='editor');area.value='編集中の下書き';area.selectionStart=5;area.selectionEnd=5;area.events.compositionstart();area.events.input();const before=view.getDraft();await action(x,'observe').onclick();assert.deepEqual(view.getDraft(),before);assert.equal(find(x.root,e=>e.dataset.test==='editor'),area);assert.equal(area.value,'編集中の下書き');view.setLocale('en');assert.deepEqual(view.getDraft(),before);view.destroy();await view.applicationCleanup();});
test('reference-locale-updates-labels',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});view.setLocale('en');assert.equal(action(x,'inquire').textContent,'Inquire original ID');assert.match(x.root.textContent,/experiment/i);view.destroy();await view.applicationCleanup();});
test('reference-destroy-cancels-connection-not-record',async()=>{const x=await rendered();await x.e.stage('6f'.repeat(16),0);const before=cp(await x.store.load());const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});view.destroy();await view.applicationCleanup();assert.equal(x.e.current.lifecycle,'DETACHED');assert.deepEqual(await x.store.load(),before);assert.equal(x.root.textContent,'');});
test('reference-dispose-reports-close-failure',async()=>{const x=await rendered();x.port.close=async()=>{throw Error('close')};const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});view.destroy();await assert.rejects(view.applicationCleanup());assert.equal(x.e.current.lifecycle,'CLEANUP_UNCONFIRMED');});
test('reference-authority-change-disconnects-with-draft-kept',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});const next=cp(x.note);next.sequence=String(BigInt(next.sequence)+1n);next.revision='revision-new';next.authority.controlHead='b'.repeat(64);view.update(next);await view.applicationCleanup();assert.notEqual(x.e.current.lifecycle,'ATTACHED');assert.equal(view.getDraft().text,'Hello');view.destroy();});
test('cancel-during-stage-stops-after-save-without-send',async()=>{const x=await attached(),started=defer(),finish=defer();const save=x.store.save;x.store.save=async v=>{started.resolve();await finish.promise;await save(v);};const p=x.e.stage('6f'.repeat(16),0);p.catch(()=>{});await started.promise;x.e.cancel();finish.resolve();await fails(()=>p,'CANCELLED');assert.equal(x.record.original.operationId,'6f'.repeat(16));assert.deepEqual(x.calls,[]);await x.e.detach();});
test('reference-authority-mismatch-before-dom-change',async()=>{const x=await rendered();x.note.authority.controlHead='f'.repeat(64);x.root.textContent='keep';assert.throws(()=>x.mountReference(x.root,x.note,{applicationEmbedding:x.e}),/APPLICATION_AUTHORITY_MISMATCH/);assert.equal(x.root.textContent,'keep');await x.e.detach();});
test('reference-second-mount-does-not-touch-either-dom',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});const d=new Document(),root=d.createElement('div');root.textContent='second';assert.throws(()=>x.mountReference(root,x.note,{applicationEmbedding:x.e}),/APPLICATION_VIEW_OWNED/);assert.equal(root.textContent,'second');view.destroy();await view.applicationCleanup();});
test('reference-invalid-input-stays-visible',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});find(x.root,e=>e.dataset.applicationField==='operationId').value='not-an-id';await action(x,'stage').onclick();assert.match(find(x.root,e=>e.dataset.applicationReason==='true').textContent,/APPLICATION_INPUT_INVALID/);assert.deepEqual(x.calls,[]);view.destroy();await view.applicationCleanup();});
test('nested-getter-not-executed',async()=>{const x=await attached();let accessed=0;const raw=cp(F.empty);Object.defineProperty(raw.journal,'receipt',{enumerable:true,get(){accessed++;return null;}});x.port.request=async()=>raw;await assert.rejects(x.e.observe());assert.equal(accessed,0);await x.e.detach();});
test('cyclic-reply-rejected',async()=>{const x=await attached();const raw=cp(F.empty);raw.journal.receipt=raw;x.port.request=async()=>raw;await assert.rejects(x.e.observe());assert.equal(x.e.current.snapshot,null);await x.e.detach();});
test('nonplain-reply-rejected',async()=>{const x=await attached();const raw=cp(F.empty);Object.setPrototypeOf(raw.journal,{inherited:true});x.port.request=async()=>raw;await assert.rejects(x.e.observe());await x.e.detach();});
test('reference-reconnect-then-destroy-closes-new-port',async()=>{const x=await rendered();const view=x.mountReference(x.root,x.note,{applicationEmbedding:x.e});await action(x,'disconnect').onclick();assert.equal(x.e.current.lifecycle,'DETACHED');x.e.attach(F.context,x.port);view.destroy();await view.applicationCleanup();assert.equal(x.e.current.lifecycle,'DETACHED');assert.equal(x.closed,2);});
test('restore-readback-original-change-is-rejected',async()=>{const x=await staged();await x.e.detach();const value=cp(x.record);let loads=0;x.store.load=async()=>{const r=cp(value);if(++loads===2)r.original.operationId='a'.repeat(32);return r;};const e=new api.ApplicationEmbedding(F.context,x.store,F.targets,{localExperiment:true});e.attach(F.context,x.port);await fails(()=>e.restore(),'CALLER_INTENT_CONFLICT');assert.equal(e.current.original.operationId,value.original.operationId);assert.equal(e.current.caller,'UNCERTAIN');await e.detach();});
test('restore-readback-marker-regression-is-rejected',async()=>{const x=await prepared();await x.e.dispatch();await x.e.detach();const value=cp(x.record);let loads=0;x.store.load=async()=>{const r=cp(value);if(++loads===2)r.dispatchAttempted=false;return r;};const e=new api.ApplicationEmbedding(F.context,x.store,F.targets,{localExperiment:true});e.attach(F.context,x.port);await fails(()=>e.restore(),'CALLER_MARKER_MISSING');assert.equal(e.current.dispatchAttempted,true);assert.equal(e.current.caller,'UNCERTAIN');await e.detach();});
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));process.exit(0);}
const cases=[];for(const t of tests){try{await t.run();cases.push({id:t.id,status:'PASS'});}catch(e){cases.push({id:t.id,status:'FAIL'});console.error(t.id,e.stack);}}
if(process.env.HARNESS_RESULT_PATH)writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));
console.log(JSON.stringify({cases}));process.exitCode=cases.some(x=>x.status!=='PASS')?1:0;
