import {readFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {webcrypto,createDecipheriv,hkdfSync} from 'node:crypto';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
const ROOT=process.env.PAR_ROOT||path.resolve(import.meta.dirname,'../../../..');
const LIB=process.env.PAR_PRESENTER_BUILD||path.join(ROOT,'product/wp11/lib');
const core=await import(pathToFileURL(path.join(LIB,'index.js')));
const canon=v=>Array.isArray(v)?'['+v.map(canon).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}':JSON.stringify(v);
const cases=[];const t=(id,fn)=>cases.push({id:'draft-vault.'+id,fn});
let vault,FilePort;
async function modules(){
 assert.ok(await fs.stat(path.join(LIB,'draft-vault.js')).catch(()=>null),'encrypted private draft module must exist');
 vault??=await import(pathToFileURL(path.join(LIB,'draft-vault.js')));
 FilePort??=(await import(pathToFileURL(path.join(ROOT,'product/wp11/adapters/file-draft-store.mjs')))).FileDraftStore;
}
const scope={appId:'org.example.notes',spaceId:'space-1',documentId:'note-1'};
const key=new Uint8Array(32).fill(42);
const draft=()=>core.reduceDraft(core.createDraft('base','frontier-1'),{type:'input',text:'秘密の下書き🔑',anchor:0,focus:0});
async function setup(){await modules();const dir=await fs.mkdtemp(path.join(tmpdir(),'par-private-'));await fs.chmod(dir,0o700);const port=new FilePort(dir);const v=new vault.DraftVault(webcrypto,port,key,scope);return {dir,port,v,async close(){v.close();await fs.rm(dir,{recursive:true,force:true});}};}
async function withVault(fn){const x=await setup();try{await fn(x);}finally{await x.close();}}
const rejectsCode=(f,code)=>assert.rejects(f,e=>e.code===code);
t('feature_exists',async()=>modules());
t('roundtrip',()=>withVault(async({v})=>{const p=await v.prepare(draft(),0,'op-1');const r=await v.commit(p);assert.equal(r.version,1);assert.equal(r.sharedSaved,false);const x=await v.load();assert.equal(x.draft.text,draft().text);assert.equal(x.draft.persisted,false);}));
t('plaintext_not_on_disk',()=>withVault(async({dir,v})=>{await v.commit(await v.prepare(draft(),0,'op-1'));const all=await Promise.all((await fs.readdir(dir)).map(f=>fs.readFile(path.join(dir,f),'utf8')));assert.ok(all.every(s=>!s.includes('秘密')&&!s.includes('baseText')));}));
t('node_crypto_crosscheck',()=>withVault(async({v,port})=>{await v.commit(await v.prepare(draft(),0,'op-x'));const row=await port.read(await v.slot());const e=JSON.parse(row.value);const hdr={schema:1,profile:e.profile,slot:e.slot,version:e.version,operationId:e.operationId,salt:e.salt,iv:e.iv};const canon=(o)=>Array.isArray(o)?'['+o.map(canon).join(',')+']':o&&typeof o==='object'?'{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+canon(o[k])).join(',')+'}':JSON.stringify(o);const k=hkdfSync('sha256',key,Buffer.from(e.salt,'hex'),Buffer.from('PAR/private-draft/key/v1'),32);const d=createDecipheriv('aes-256-gcm',k,Buffer.from(e.iv,'hex'));d.setAAD(Buffer.from(canon(hdr)));const c=Buffer.from(e.ciphertext,'hex');d.setAuthTag(c.subarray(-16));const plain=Buffer.concat([d.update(c.subarray(0,-16)),d.final()]);assert.equal(JSON.parse(plain.toString()).draft.text,draft().text);}));
t('wrong_key_refused',()=>withVault(async({v,port})=>{await v.commit(await v.prepare(draft(),0,'op-1'));const w=new vault.DraftVault(webcrypto,port,new Uint8Array(32).fill(43),scope);await rejectsCode(()=>w.load(),'DRAFT_AUTH_FAILED');await rejectsCode(()=>w.prepare(draft(),1,'overwrite'),'DRAFT_AUTH_FAILED');}));
t('scope_swap_refused',()=>withVault(async({v,port})=>{await v.commit(await v.prepare(draft(),0,'op-1'));const old=await port.read(await v.slot());const w=new vault.DraftVault(webcrypto,port,key,{...scope,documentId:'other'});await port.compareAndSwap(await w.slot(),0,old);await rejectsCode(()=>w.load(),'DRAFT_SCOPE_MISMATCH');}));
t('ciphertext_tamper_refused',()=>withVault(async({v,port,dir})=>{await v.commit(await v.prepare(draft(),0,'op-1'));const slot=await v.slot();const row=structuredClone(await port.read(slot));const e=JSON.parse(row.value);e.ciphertext=(e.ciphertext[0]==='a'?'b':'a')+e.ciphertext.slice(1);row.value=canon(e);await fs.writeFile(path.join(dir,slot+'.json'),canon(row),{mode:0o600});await rejectsCode(()=>v.load(),'DRAFT_AUTH_FAILED');}));
t('stale_writer_refused',()=>withVault(async({v,port})=>{const other=new vault.DraftVault(webcrypto,port,key,scope);const a=await v.prepare(draft(),0,'a'), b=await other.prepare(draft(),0,'b');await v.commit(a);await rejectsCode(()=>other.commit(b),'DRAFT_CONFLICT');}));
t('same_prepared_retry_no_reencrypt',()=>withVault(async({v})=>{const a=await v.prepare(draft(),0,'a');const r=await v.commit(a);assert.deepEqual(await v.commit(a),r);}));
t('new_op_same_id_refused',()=>withVault(async({v})=>{await v.commit(await v.prepare(draft(),0,'a'));await rejectsCode(()=>v.prepare(draft(),1,'a'),'OPERATION_REUSED');}));
t('state_copied_before_async',()=>withVault(async({v})=>{const d=structuredClone(draft());const promise=v.prepare(d,0,'a');d.text='changed';const p=await promise;await v.commit(p);assert.equal((await v.load()).draft.text,draft().text);}));
t('prepared_tamper_refused',()=>withVault(async({v})=>{const p=structuredClone(await v.prepare(draft(),0,'a'));p.row.value+=' ';await rejectsCode(()=>v.commit(p),'PREPARED_MISMATCH');}));
t('close_blocks_future_io',()=>withVault(async({v})=>{const p=await v.prepare(draft(),0,'a');v.close();await rejectsCode(()=>v.commit(p),'DRAFT_LOCKED');await rejectsCode(()=>v.load(),'DRAFT_LOCKED');}));
t('delete_keeps_version_tombstone',()=>withVault(async({v})=>{await v.commit(await v.prepare(draft(),0,'a'));await v.commit(await v.prepare(null,1,'delete'));const x=await v.load();assert.equal(x.draft,null);assert.equal(x.version,2);await rejectsCode(()=>v.prepare(draft(),0,'stale'),'DRAFT_CONFLICT');}));
t('restore_never_restores_composition',()=>withVault(async()=>{const states=JSON.parse(await fs.readFile(path.join(ROOT,'product/wp11/fixtures/states.json')));const s=structuredClone(states.find(x=>x.state.scope.documentId!==null).state);const d=core.reduceDraft(draft(),{type:'composition-start'});const r=vault.restoreDraft(d,s);assert.equal(r.composing,false);assert.equal(r.text,d.text);assert.equal(r.persisted,false);}));
t('restore_changed_base_requires_review',()=>withVault(async()=>{const states=JSON.parse(await fs.readFile(path.join(ROOT,'product/wp11/fixtures/states.json')));const r=vault.restoreDraft(draft(),states.find(x=>x.state.scope.documentId!==null).state);assert.equal(r.requiresRebase,true);}));
t('no_key_in_port',()=>withVault(async({dir,v})=>{await v.commit(await v.prepare(draft(),0,'a'));for(const f of await fs.readdir(dir)){assert.ok(!(await fs.readFile(path.join(dir,f),'utf8')).includes(Buffer.from(key).toString('hex')));}}));
t('restart_child_loads_ciphertext',()=>withVault(async({dir,v})=>{await v.commit(await v.prepare(draft(),0,'a'));const js=`import {DraftVault} from ${JSON.stringify(pathToFileURL(path.join(LIB,'draft-vault.js')).href)};import {FileDraftStore} from ${JSON.stringify(pathToFileURL(path.join(ROOT,'product/wp11/adapters/file-draft-store.mjs')).href)};const v=new DraftVault(crypto,new FileDraftStore(${JSON.stringify(dir)}),new Uint8Array(32).fill(42),${JSON.stringify(scope)});console.log(JSON.stringify(await v.load()));`;const p=spawnSync(process.execPath,['--input-type=module','-e',js],{encoding:'utf8',timeout:15000});assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).draft.text,draft().text);}));
for(const [name,mutate] of [['version',e=>e.version++],['profile',e=>e.profile='other'],['salt',e=>e.salt='bad'],['iv',e=>e.iv='00'],['unknown_field',e=>e.unknown=true]])t('reject_envelope_'+name,()=>withVault(async({dir,v,port})=>{await v.commit(await v.prepare(draft(),0,'a'));const slot=await v.slot();const r=structuredClone(await port.read(slot));const e=JSON.parse(r.value);mutate(e);r.value=canon(e);await fs.writeFile(path.join(dir,slot+'.json'),canon(r),{mode:0o600});await assert.rejects(()=>v.load());}));
for(const [name,d] of [['bool_version',true],['negative_version',-1],['unsafe_version',Number.MAX_SAFE_INTEGER],['fraction_version',1.5]])t('reject_'+name,()=>withVault(async({v})=>{await assert.rejects(()=>v.prepare(draft(),d,'x'));}));
t('null_document_scope_refused',async()=>{await modules();assert.throws(()=>new vault.DraftVault(webcrypto,{},key,{...scope,documentId:null}));});
t('short_key_refused',async()=>{await modules();assert.throws(()=>new vault.DraftVault(webcrypto,{},new Uint8Array(16),scope));});
t('file_permissions_refused',()=>withVault(async({dir,v})=>{await fs.chmod(dir,0o755);await assert.rejects(()=>v.load());await fs.chmod(dir,0o700);}));
t('file_symlink_refused',()=>withVault(async({dir,v})=>{const slot=await v.slot();await fs.symlink('/etc/hosts',path.join(dir,slot+'.json'));await assert.rejects(()=>v.load());}));
t('live_lock_refused',()=>withVault(async({dir,v})=>{const p=await v.prepare(draft(),0,'a');await fs.writeFile(path.join(dir,'.writer.lock'),JSON.stringify({pid:process.pid}),{mode:0o600});await rejectsCode(()=>v.commit(p),'DRAFT_WRITE_UNKNOWN');await rejectsCode(()=>FilePort.recoverLock(dir),'WRITER_ACTIVE');}));
for(const stage of ['temp-synced','published','directory-synced'])t('sigkill_'+stage,()=>withVault(async({dir,v})=>{const p=await v.prepare(draft(),0,'a');const js=`import {FileDraftStore} from ${JSON.stringify(pathToFileURL(path.join(ROOT,'product/wp11/adapters/file-draft-store.mjs')).href)};const s=new FileDraftStore(${JSON.stringify(dir)},{boundary:n=>{if(n===${JSON.stringify(stage)})process.kill(process.pid,'SIGKILL')}});await s.compareAndSwap(${JSON.stringify(p.slot)},0,${JSON.stringify(p.row)});`;const c=spawnSync(process.execPath,['--input-type=module','-e',js],{encoding:'utf8',timeout:15000});assert.equal(c.signal,'SIGKILL',c.stderr);const x=await v.load();assert.equal(x.version,stage==='temp-synced'?0:1);await FilePort.recoverLock(dir);await v.commit(p);assert.equal((await v.load()).version,1);}));
t('full_unicode_and_selection',()=>withVault(async({v})=>{const d=core.reduceDraft(core.createDraft('','f'),{type:'input',text:'a😀e\u0301日本語',anchor:3,focus:8});await v.commit(await v.prepare(d,0,'a'));assert.deepEqual((await v.load()).draft,d);}));
t('unknown_write_reconciles',()=>withVault(async({v,port})=>{const p=await v.prepare(draft(),0,'a');const original=port.compareAndSwap.bind(port);port.compareAndSwap=async(...args)=>{await original(...args);throw Error('reply lost');};await rejectsCode(()=>v.commit(p),'DRAFT_WRITE_UNKNOWN');assert.equal((await v.inspect(p)).state,'CONFIRMED');}));
t('capabilities_not_replication',()=>withVault(async({v})=>{const r=await v.commit(await v.prepare(draft(),0,'a'));assert.equal(r.replicated,false);assert.equal(r.sharedSaved,false);assert.equal(r.durability,'posix-fsync-candidate');}));

t('session_unknown_blocks_blind_retry',()=>withVault(async({v,port})=>{const {VaultDraftSession}=await import(pathToFileURL(path.join(LIB,'draft-session.js')));const session=new VaultDraftSession(v);const original=port.compareAndSwap.bind(port);port.compareAndSwap=async(...args)=>{await original(...args);throw Error('lost');};await rejectsCode(()=>session.save(draft(),0,'a'),'DRAFT_WRITE_UNKNOWN');await rejectsCode(()=>session.save(draft(),0,'b'),'DRAFT_RECONCILE_REQUIRED');assert.equal(await session.reconcile(),'CONFIRMED');}));
t('idb_absent_no_fallback',async()=>{const m=await import(pathToFileURL(path.join(LIB,'indexeddb-drafts.js')));await rejectsCode(()=>m.openIndexedDbDraftStore(undefined),'DRAFT_STORAGE_UNAVAILABLE');});
t('hardlink_refused',()=>withVault(async({v,dir})=>{await v.commit(await v.prepare(draft(),0,'a'));const f=path.join(dir,(await v.slot())+'.json');await fs.link(f,path.join(dir,'linked'));await assert.rejects(()=>v.load());}));
t('noncanonical_duplicate_json_refused',()=>withVault(async({v,dir})=>{await v.commit(await v.prepare(draft(),0,'a'));const f=path.join(dir,(await v.slot())+'.json');const s=await fs.readFile(f,'utf8');await fs.writeFile(f,s.replace('"version":1','"version":1,"version":1'));await assert.rejects(()=>v.load());}));
t('only_current_head_op_retained',()=>withVault(async({v})=>{await v.commit(await v.prepare(draft(),0,'a'));await v.commit(await v.prepare(draft(),1,'b'));await rejectsCode(()=>v.prepare(draft(),0,'a'),'DRAFT_CONFLICT');}));
t('reject_split_surrogate_selection',()=>withVault(async({v})=>{const d=structuredClone(core.createDraft('😀','f'));d.selection={anchor:1,focus:1};await assert.rejects(()=>v.prepare(d,0,'bad'));assert.equal((await v.load()).version,0);}));
t('key_buffer_copied',()=>withVault(async({port})=>{const k=new Uint8Array(32).fill(42);const v=new vault.DraftVault(webcrypto,port,k,scope);k.fill(0);await v.commit(await v.prepare(draft(),0,'a'));const another=new vault.DraftVault(webcrypto,port,key,scope);assert.equal((await another.load()).draft.text,draft().text);}));
t('receipt_rejects_shared_claim',async()=>{const m=await import(pathToFileURL(path.join(LIB,'draft-session.js')));assert.throws(()=>m.checkDraftReceipt({version:1,operationId:'a',slot:'a'.repeat(64),ciphertextHash:'b'.repeat(64),durability:'browser-best-effort',sharedSaved:true,replicated:false},0,'a'));});
t('restored_base_does_not_grant_write',()=>withVault(async()=>{const states=JSON.parse(await fs.readFile(path.join(ROOT,'product/wp11/fixtures/states.json')));const s=structuredClone(states[1].state);s.authority.sharedWriteAllowed=false;s.authority.role='reader';const d=core.createDraft(s.document.text,s.document.frontier);assert.equal(vault.restoreDraft(d,s).requiresRebase,true);}));

t('cleanup_failure_is_not_success',()=>withVault(async({dir,v,port})=>{port.boundary=name=>{if(name==='directory-synced'){const {token}=JSON.parse(readFileSync(path.join(dir,'.writer.lock'),'utf8'));mkdirSync(path.join(dir,'.draft-'+token+'.tmp'));}};const p=await v.prepare(draft(),0,'cleanup');await rejectsCode(()=>v.commit(p),'DRAFT_WRITE_UNKNOWN');assert.equal((await v.inspect(p)).state,'CONFIRMED');}));
if(process.argv.includes('--list')){console.log(JSON.stringify(cases.map(c=>c.id)));process.exit(0);}
const results=[];for(const c of cases){try{await c.fn();results.push({id:c.id,status:'PASS'});}catch(e){results.push({id:c.id,status:'FAIL'});console.error(c.id,e.stack);}}
if(process.env.HARNESS_RESULT_PATH)await fs.writeFile(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases:results}));
console.log(JSON.stringify({scope:'PRIVATE_DRAFT_NODE_FILE_ONLY_NOT_IDB_OR_SHARED_RUNTIME',cases:results,result:results.every(c=>c.status==='PASS')?'PASS':'FAIL'},null,2));process.exitCode=results.some(c=>c.status!=='PASS')?1:0;
