import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const ROOT=process.env.PAR_ROOT,LIB=process.env.PAR_PRESENTER_BUILD||path.join(ROOT,'product/wp11/lib');
const cases=[];const test=(id,fn)=>cases.push({id:'runtime.binding.'+id,fn});
let api,raw;
async function setup(){api??=await import(pathToFileURL(path.join(LIB,'index.js')));assert.equal(typeof api.RuntimeBinding,'function','runtime binding missing');raw??=JSON.parse(await fs.readFile(process.env.PAR_OBSERVATION_FIXTURE,'utf8'));return structuredClone(raw);}
const pin=r=>({scope:r.scope,deviceId:r.deviceId,storeGeneration:r.storeGeneration,streamId:r.streamId});
const command=s=>({schemaVersion:1,kind:'inspect-operation',expectedRevision:s.revision,streamId:s.streamId,sequence:s.sequence,scope:s.scope,operationId:s.local.operationId,confirmation:null});
const port=f=>({observe:async()=>f.committed,inspectOperation:async()=>f.committed});
const rejects=(fn,code)=>assert.rejects(fn,e=>e.code===code);
test('unknown_local_is_not_failed',async()=>{const f=await setup(),s=api.projectRuntimeObservation(f.unknown,pin(f.unknown));assert.equal(s.local.state,'unknown');assert.equal(s.connection.state,'unknown');assert.equal(api.present(s).sharedWriteEligible,false);});
test('real_receipt_projects_committed_not_applied',async()=>{const f=await setup(),s=api.projectRuntimeObservation(f.committed,pin(f.committed));assert.equal(s.local.state,'committed');assert.equal(s.document.applied,false);assert.equal(s.document.innerValidated,false);assert.equal(s.document.text,'');assert.equal(s.protection.observations.length,0);assert.equal(s.authority.sharedWriteAllowed,false);});
test('operation_inquiry_offered',async()=>{const f=await setup(),s=api.projectRuntimeObservation(f.unknown,pin(f.unknown));assert.equal(api.present(s).actions.find(x=>x.kind==='inspect-operation').enabled,true);});
test('actual_saved_result_via_port',async()=>{const f=await setup();let count=0;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{observe:async()=>f.committed,inspectOperation:async id=>{assert.equal(id,f.unknown.operation.id);count++;return f.committed;}});const result=await b.execute(api.prepareCommand(b.current,command(b.current)));assert.equal(result.outcome,'observed');assert.equal(result.observation.local.state,'committed');assert.equal(count,1);});
test('stale_command_no_host_call',async()=>{const f=await setup();let n=0;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{...port(f),inspectOperation:async()=>{n++;return f.committed;}});const c=command(b.current);c.expectedRevision='stale';await rejects(()=>b.execute({kind:'intent',command:c,effectExecuted:false,requiresDomainRevalidation:true,recoveryActivation:null}),'STALE_VIEW');assert.equal(n,0);});
test('unknown_result_does_not_auto_retry',async()=>{const f=await setup();let count=0;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{...port(f),inspectOperation:async()=>{count++;throw Error('lost');}});const r=await b.execute(api.prepareCommand(b.current,command(b.current)));assert.equal(r.outcome,'unknown');assert.equal(count,1);assert.equal(b.current.local.state,'unknown');});
test('old_response_rejected',async()=>{const f=await setup();const b=new api.RuntimeBinding(pin(f.committed),f.committed,{observe:async()=>f.unknown,inspectOperation:async()=>f.unknown});await rejects(()=>b.refresh(),'STALE_VIEW');assert.equal(b.current.local.state,'committed');});
test('new_stream_requires_explicit_rebinding',async()=>{const f=await setup();const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{...port(f),observe:async()=>f.reopened});await rejects(()=>b.refresh(),'RUNTIME_BINDING_MISMATCH');});
test('same_sequence_changed_response_rejected',async()=>{const f=await setup();f.committed.sequence=f.unknown.sequence;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,port(f));await rejects(()=>b.refresh(),'REVISION_REUSED');});
test('duplicate_unchanged_response_allowed',async()=>{const f=await setup();const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{observe:async()=>f.unknown,inspectOperation:async()=>f.unknown});assert.equal((await b.refresh()).revision,f.unknown.revision);});
test('wrong_requested_operation_rejected',async()=>{const f=await setup();f.committed.operation.id='ff'.repeat(16);const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,port(f));const r=await b.execute(api.prepareCommand(b.current,command(b.current)));assert.equal(r.outcome,'unknown');assert.equal(b.current.local.state,'unknown');});
test('close_discards_pending_response',async()=>{const f=await setup();let resolve;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{observe:()=>new Promise(r=>{resolve=r;}),inspectOperation:async()=>f.committed});const p=b.refresh();b.close();resolve(f.committed);await rejects(()=>p,'RUNTIME_CLOSED');});
test('busy_rejects_parallel_call',async()=>{const f=await setup();let resolve;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{observe:()=>new Promise(r=>{resolve=r;}),inspectOperation:async()=>f.committed});const p=b.refresh();await rejects(()=>b.refresh(),'RUNTIME_BUSY');resolve(f.committed);await p;});
test('copied_snapshot_no_mutation',async()=>{const f=await setup();const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,port(f));f.unknown.authority.role='owner';assert.equal(b.current.authority.role,'editor');assert.throws(()=>{b.current.local.state='committed';});});
test('closed_rejects_future_io',async()=>{const f=await setup();const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,port(f));b.close();await rejects(()=>b.refresh(),'RUNTIME_CLOSED');});
test('commit_capability_stays_disabled',async()=>{const f=await setup();assert.equal(api.validateRuntimeObservation(f.committed).capabilities.sharedCommit,false);assert.equal(api.projectRuntimeObservation(f.changed,pin(f.changed)).authority.sharedWriteAllowed,false);});
for(const [name,fn] of [
 ['schema',r=>r.profile='wrong'],['store',r=>r.storeGeneration='ee'.repeat(16)],['scope',r=>r.scope.documentId='ee'.repeat(32)],['device',r=>r.deviceId='ee'.repeat(32)],
 ['applied',r=>r.document.applied=true],['inner',r=>r.document.innerValidated=true],['plaintext',r=>r.document.text='unverified text'],['catalog',r=>r.document.catalogComplete=true],
 ['replication',r=>r.replicationObserved=true],['product',r=>r.productQualified=true],['latest',r=>r.globalLatestProven=true],['commit',r=>r.capabilities.sharedCommit=true],['sync',r=>r.capabilities.sync=true],['crdt',r=>r.capabilities.crdtApply=true],
 ['receipt',r=>r.operation.receiptVerified=false],['commit_id',r=>r.operation.commitId=null],['operation_id',r=>r.operation.id=null],['sequence_bool',r=>r.sequence=true],['sequence_overflow',r=>r.sequence='18446744073709551616'],
 ['count_bool',r=>r.document.envelopeCount=true],['pending_count',r=>r.document.pendingCount=3],['unknown_field',r=>r.surprise=true],['timestamp',r=>r.observedAt='today'],['unknown_authority',r=>r.authority.state='magic']
])test('reject_'+name,async()=>{const f=await setup();const p=structuredClone(pin(f.committed));fn(f.committed);assert.throws(()=>api.projectRuntimeObservation(f.committed,p));});
test('no_replication_wait_claim_without_runtime',async()=>{const f=await setup();const vm=api.present(api.projectRuntimeObservation(f.committed,pin(f.committed)));assert.equal(vm.protection.message.key,'copies.not-observed');});
test('inert_intent_tamper_refused',async()=>{const f=await setup();const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,port(f));const i=structuredClone(api.prepareCommand(b.current,command(b.current)));i.effectExecuted=true;await rejects(()=>b.execute(i),'INVALID_INPUT');});
test('unsupported_operation_never_calls_port',async()=>{const f=await setup();let n=0;const b=new api.RuntimeBinding(pin(f.unknown),f.unknown,{observe:async()=>{n++;return f.committed;},inspectOperation:async()=>{n++;return f.committed;}});const c=command(b.current);c.kind='open-details';assert.equal((await b.execute(api.prepareCommand(b.current,c))).outcome,'unavailable');assert.equal(n,0);});
if(process.argv.includes('--list')){console.log(JSON.stringify(cases.map(x=>x.id)));process.exit(0);}
const results=[];for(const c of cases){try{await c.fn();results.push({id:c.id,status:'PASS'});}catch(e){results.push({id:c.id,status:'FAIL'});console.error(c.id,e.stack);}}
if(process.env.HARNESS_RESULT_PATH)await fs.writeFile(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases:results}));
console.log(JSON.stringify({cases:results,result:results.every(x=>x.status==='PASS')?'PASS':'FAIL'}));process.exitCode=results.some(x=>x.status!=='PASS')?1:0;
