import assert from 'node:assert/strict';
import {existsSync,readFileSync,writeFileSync,mkdtempSync,chmodSync,symlinkSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';
const R=process.env.PAR_ROOT||resolve(new URL('../../../',import.meta.url).pathname);
const modulePath=join(R,'product/wp11/lib/application-owner.js');
const storagePath=join(R,'product/wp11/node/caller-intent.mjs');
const tests=[];const test=(n,f)=>tests.push(['application.owner.'+n,f]);
const copy=v=>JSON.parse(JSON.stringify(v));let m,F;
async function setup(){
 assert.ok(existsSync(modulePath),'typed anchored client missing');m=await import(pathToFileURL(modulePath));
 F=JSON.parse(readFileSync(process.env.PAR_APPLICATION_FIXTURE,'utf8'));
 let saved=null,attempted=false;const calls=[];
 const store={async load(){return saved?{original:copy(saved),dispatchAttempted:attempted}:null;},async save(v){if(saved)assert.deepEqual(v,saved);saved=copy(v);},async markDispatch(id){assert.equal(id,saved.operationId);if(attempted)throw Object.assign(Error(),{code:'CALLER_DISPATCH_ALREADY_RECORDED'});attempted=true;}};
 const port={async request(op,args,signal){calls.push({op,args});assert.equal(signal.aborted,false);return copy(({observe:F.empty,prepare:F.prepared,dispatch:F.observed,inquire:F.inquired,retire:F.retired})[op]);},async close(){}};
 return{store,port,calls,client:new m.ApplicationOwnerClient(F.context,port,store),get saved(){return saved;},get attempted(){return attempted;}};
}
async function prepared(){const x=await setup();await x.client.observe();await x.client.prepare('6f'.repeat(16),0,F.targets);return x;}

test('protocol-distinct',async()=>{const x=await setup();assert.equal(m.APPLICATION_OWNER_PROTOCOL,'par-owner-application-0052');await x.client.observe();assert.equal(x.client.current.snapshot.journal.state,'EMPTY');});
test('store-required',async()=>{await setup();assert.throws(()=>new m.ApplicationOwnerClient(F.context,{},null));});
test('persist-before-prepare-send',async()=>{const x=await setup();await x.client.observe();const old=x.port.request;x.port.request=async(...a)=>{assert.equal(x.saved.operationId,'6f'.repeat(16));return old(...a);};await x.client.prepare('6f'.repeat(16),0,F.targets);});
test('failed-save-does-not-send',async()=>{const x=await setup();await x.client.observe();x.store.save=async()=>{throw Error('disk');};await assert.rejects(x.client.prepare('6f'.repeat(16),0,F.targets));assert.equal(x.calls.length,1);assert.equal(x.client.current.original.operationId,'6f'.repeat(16));});
test('wrong-target-before-save',async()=>{const x=await setup();await x.client.observe();await assert.rejects(x.client.prepare('6f'.repeat(16),0,['0'.repeat(64)]));assert.equal(x.saved,null);assert.equal(x.calls.length,1);});
test('invalid-id-before-save',async()=>{const x=await setup();await x.client.observe();await assert.rejects(x.client.prepare('oops',0,F.targets));assert.equal(x.saved,null);});
test('cancelled-before-save',async()=>{const x=await setup();await x.client.observe();const c=new AbortController();c.abort();await assert.rejects(x.client.prepare('6f'.repeat(16),0,F.targets,{signal:c.signal}));assert.equal(x.saved,null);});
test('cancel-during-save-no-send',async()=>{const x=await setup();await x.client.observe();const c=new AbortController();const save=x.store.save;x.store.save=async v=>{await save(v);c.abort();};await assert.rejects(x.client.prepare('6f'.repeat(16),0,F.targets,{signal:c.signal}));assert.equal(x.calls.length,1);assert.equal(x.saved.operationId,'6f'.repeat(16));});
test('dispatch-marker-before-send',async()=>{const x=await prepared();const old=x.port.request;x.port.request=async(...a)=>{assert.equal(x.attempted,true);return old(...a);};await x.client.dispatch();assert.equal(x.client.current.snapshot.journal.state,'OBSERVED');});
test('marker-failure-no-dispatch',async()=>{const x=await prepared();x.store.markDispatch=async()=>{throw Error('fsync lost');};await assert.rejects(x.client.dispatch());assert.equal(x.calls.filter(c=>c.op==='dispatch').length,0);assert.equal(x.client.current.needsInquiry,true);});
test('duplicate-dispatch-never-sent',async()=>{const x=await prepared();await x.client.dispatch();await assert.rejects(x.client.dispatch());assert.equal(x.calls.filter(c=>c.op==='dispatch').length,1);});
test('prepare-response-loss-retains-original',async()=>{const x=await setup();await x.client.observe();x.port.request=async()=>{throw Error('closed');};await assert.rejects(x.client.prepare('6f'.repeat(16),0,F.targets));assert.equal(x.client.current.original.operationId,'6f'.repeat(16));assert.equal(x.client.current.needsInquiry,true);});
test('reopen-load-does-not-transmit',async()=>{const x=await prepared();await x.client.dispatch();const c=new m.ApplicationOwnerClient(F.context,x.port,x.store);const n=x.calls.length;await c.restore();assert.equal(x.calls.length,n);assert.equal(c.current.dispatchAttempted,true);await assert.rejects(c.dispatch());});
test('reopen-original-inquiry',async()=>{const x=await prepared();await x.client.dispatch();const c=new m.ApplicationOwnerClient(F.context,x.port,x.store);await c.restore();await c.observe();await c.inquire();assert.equal(c.current.snapshot.journal.operationState,'OBSERVED_APPLICATION_RECORD');});
test('wrong-stored-owner-refused',async()=>{const x=await prepared();const load=x.store.load;x.store.load=async()=>{const r=await load();r.original.ownerKey='foreign';return r;};const c=new m.ApplicationOwnerClient(F.context,x.port,x.store);await assert.rejects(c.restore());});
test('context-substitution-refused',async()=>{const x=await setup();x.port.request=async()=>{const r=copy(F.empty);r.context.journalId='0'.repeat(64);return r;};await assert.rejects(x.client.observe());});
test('no-false-applied-claim',async()=>{const x=await setup();x.port.request=async()=>{const r=copy(F.empty);r.journal.applied=true;return r;};await assert.rejects(x.client.observe());});
test('old-sequence-rejected',async()=>{const x=await setup();await x.client.observe();await assert.rejects(x.client.observe());});
test('observed-without-receipt-rejected',async()=>{const x=await prepared();x.port.request=async()=>{const r=copy(F.observed);r.journal.receipt=null;return r;};await assert.rejects(x.client.dispatch());});
test('foreign-receipt-rejected',async()=>{const x=await prepared();x.port.request=async()=>{const r=copy(F.observed);r.journal.receipt.operationId='a'.repeat(32);return r;};await assert.rejects(x.client.dispatch());});
test('inquiry-failure-does-not-unlock',async()=>{const x=await prepared();await x.client.dispatch();x.port.request=async()=>{throw Error('gone');};await assert.rejects(x.client.inquire());await assert.rejects(x.client.dispatch());assert.equal(x.client.current.dispatchAttempted,true);});
test('late-response-after-close-refused',async()=>{const x=await setup();let release;x.port.request=()=>new Promise(r=>release=r);const p=x.client.observe();const caught=assert.rejects(p);await new Promise(r=>setImmediate(r));await x.client.close();release(F.empty);await caught;assert.equal(x.client.current.status,'CLOSED');});
test('single-operation',async()=>{const x=await setup();let release;x.port.request=()=>new Promise(r=>release=r);const p=x.client.observe();await assert.rejects(x.client.observe());await new Promise(r=>setImmediate(r));release(F.empty);await p;});
test('retire-explicit',async()=>{const x=await prepared();await x.client.dispatch();await x.client.retire();assert.equal(x.client.current.snapshot.journal.state,'RETIRED');assert.equal(x.attempted,true);});
test('ja-en-presenter',async()=>{const x=await prepared();assert.match(m.presentApplicationOwner(x.client.current,'ja'),/準備/);assert.match(m.presentApplicationOwner(x.client.current,'en'),/Prepared/);});
test('disk-restore-preserves-marker',async()=>{await setup();assert.ok(existsSync(storagePath),'caller disk provider missing');const{LocalCallerIntent}=await import(pathToFileURL(storagePath));const d=mkdtempSync(join(tmpdir(),'par-caller-'));try{chmodSync(d,0o700);const x=await prepared();const s=new LocalCallerIntent(d);await s.save(x.saved);await s.markDispatch(x.saved.operationId);const r=await new LocalCallerIntent(d).load();assert.deepEqual(r,{original:x.saved,dispatchAttempted:true});await assert.rejects(s.markDispatch(x.saved.operationId));}finally{rmSync(d,{recursive:true,force:true});}});
test('disk-conflict-refused',async()=>{await setup();assert.ok(existsSync(storagePath));const{LocalCallerIntent}=await import(pathToFileURL(storagePath));const d=mkdtempSync(join(tmpdir(),'par-caller-'));try{chmodSync(d,0o700);const x=await prepared();const s=new LocalCallerIntent(d);await s.save(x.saved);await assert.rejects(s.save({...x.saved,operationId:'a'.repeat(32)}));}finally{rmSync(d,{recursive:true,force:true});}});
test('disk-corrupt-not-empty',async()=>{await setup();assert.ok(existsSync(storagePath));const{LocalCallerIntent}=await import(pathToFileURL(storagePath));const d=mkdtempSync(join(tmpdir(),'par-caller-'));try{chmodSync(d,0o700);writeFileSync(join(d,'original.json'),'{',{mode:0o600});await assert.rejects(new LocalCallerIntent(d).load());}finally{rmSync(d,{recursive:true,force:true});}});
test('disk-world-readable-refused',async()=>{await setup();assert.ok(existsSync(storagePath));const{LocalCallerIntent}=await import(pathToFileURL(storagePath));const d=mkdtempSync(join(tmpdir(),'par-caller-'));try{chmodSync(d,0o755);await assert.rejects(new LocalCallerIntent(d).load());}finally{rmSync(d,{recursive:true,force:true});}});
test('disk-symlink-refused',async()=>{await setup();assert.ok(existsSync(storagePath));const{LocalCallerIntent}=await import(pathToFileURL(storagePath));const d=mkdtempSync(join(tmpdir(),'par-caller-'));try{chmodSync(d,0o700);writeFileSync(join(d,'other'), '{}',{mode:0o600});symlinkSync(join(d,'other'),join(d,'original.json'));await assert.rejects(new LocalCallerIntent(d).load());}finally{rmSync(d,{recursive:true,force:true});}});
test('reply-owned-before-asynchronous-hash',async()=>{const x=await setup();const raw=copy(F.empty);x.port.request=async()=>raw;const digest=crypto.subtle.digest;let changed=false;crypto.subtle.digest=function(...args){if(!changed){changed=true;raw.journal.applied=true;}return digest.apply(this,args);};try{const r=await x.client.observe();assert.equal(r.journal.applied,false);}finally{crypto.subtle.digest=digest;}});
test('marker-response-loss-recovered-no-replay',async()=>{const x=await prepared();const mark=x.store.markDispatch;x.store.markDispatch=async id=>{await mark(id);throw Error('reply lost');};await assert.rejects(x.client.dispatch());assert.equal(x.calls.filter(c=>c.op==='dispatch').length,0);const c=new m.ApplicationOwnerClient(F.context,x.port,x.store);await c.restore();assert.equal(c.current.dispatchAttempted,true);await assert.rejects(c.dispatch());});
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(x=>x[0]).sort()));process.exit(0);}
const cases=[];for(const[id,fn]of tests){try{await fn();cases.push({id,status:'PASS'});}catch(e){cases.push({id,status:'FAIL'});console.error(id,e.stack);}}
console.log(JSON.stringify({cases,nonce:process.env.HARNESS_NONCE||'standalone'}));if(process.env.HARNESS_RESULT_PATH)writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,cases,nonce:process.env.HARNESS_NONCE||'standalone'}));process.exitCode=cases.some(x=>x.status!=='PASS')?1:0;
