import assert from 'node:assert/strict';import {Duplex} from 'node:stream';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const ROOT=process.env.PAR_ROOT||process.cwd(),tests=[];const test=(id,fn)=>tests.push({id:'event-host.channel.'+id,fn});let Channel;
const ctx={protocol:'par-sdk-events-local-0038',appId:'test.app',spaceId:'11'.repeat(32),streamId:'22'.repeat(32),epoch:'1',schema:{body:'text'},schemaDigest:'33'.repeat(32),issuer:'44'.repeat(32),consumerId:'55'.repeat(16),journalGeneration:'66'.repeat(32)};
const hello=()=>({v:1,kind:'hello',protocol:'par-owner-event-host-0039',hostId:'aa'.repeat(16),context:ctx,maxRequest:65536,maxResponse:1500000});
function frame(v){const raw=typeof v==='string'?Buffer.from(v):Buffer.from(JSON.stringify(v)),h=Buffer.alloc(4);h.writeUInt32BE(raw.length);return Buffer.concat([h,raw])}
class Peer extends Duplex{writes=[];_read(){} _write(b,e,cb){this.writes.push(Buffer.from(b));cb()}feed(x){this.push(frame(x))}}
function setup(options={}){assert.ok(Channel,'connected channel absent');const peer=new Peer();const channel=new Channel(peer,{expectedContext:ctx,...options});return {peer,channel}}
async function ready(){const x=setup();x.peer.feed(hello());await x.channel.ready;return x}
const sig=()=>new AbortController().signal;
test('hello-split-at-every-byte',async()=>{const {peer,channel}=setup();for(const b of frame(hello()))peer.push(Buffer.from([b]));assert.equal((await channel.ready).hostId,'aa'.repeat(16));await channel.close()});
for(const [id,raw] of [['zero-length',Buffer.alloc(4)],['oversize-length',Buffer.from([0,0x16,0xe3,0x61])],['invalid-utf8',Buffer.from([0,0,0,2,0xc0,0xaf])]])test(id,async()=>{const {peer,channel}=setup();peer.push(raw);await assert.rejects(channel.ready);assert.equal(channel.stats().closed,true);await channel.close()});
test('duplicate-json-key',async()=>{const {peer,channel}=setup();peer.feed('{"v":1,"v":1}');await assert.rejects(channel.ready);await channel.close()});
test('wrong-context',async()=>{const {peer,channel}=setup();const h=hello();h.context={...ctx,epoch:'2'};peer.feed(h);await assert.rejects(channel.ready);await channel.close()});
test('response-cap-cannot-be-raised-by-peer',async()=>{const {peer,channel}=setup();peer.feed({...hello(),maxResponse:9999999});await assert.rejects(channel.ready);await channel.close()});
test('abort-before-write',async()=>{const {peer,channel}=await ready(),ac=new AbortController();ac.abort();await assert.rejects(channel.request('poll',{},ac.signal),e=>e.code==='CANCELLED');assert.equal(peer.writes.length,0);await channel.close()});
test('unexposed-operation',async()=>{const {peer,channel}=await ready();await assert.rejects(channel.request('publish',{},sig()),e=>e.code==='HOST_OPERATION_DENIED');assert.equal(peer.writes.length,0);await channel.close()});
test('bounded-pending-requests',async()=>{const {channel}=await ready();const p1=channel.request('poll',{},sig()).catch(e=>e.code),p2=channel.request('cancel',{},sig()).catch(e=>e.code);await assert.rejects(channel.request('cursor',{},sig()),e=>e.code==='HOST_CHANNEL_BUSY');assert.equal(channel.stats().inflight,2);await channel.close();assert.equal(await p1,'HOST_DISCONNECTED');await p2});
test('wrong-correlation-terminates-channel',async()=>{const {peer,channel}=await ready();const p=channel.request('poll',{},sig());peer.feed({v:1,id:'2',op:'poll',value:{}});await assert.rejects(p);assert.equal(channel.stats().closed,true);await channel.close()});
test('wrong-operation-terminates-channel',async()=>{const {peer,channel}=await ready();const p=channel.request('poll',{},sig());peer.feed({v:1,id:'1',op:'ack',value:{}});await assert.rejects(p);await channel.close()});
test('explicit-reply-only-resolves-matching-call',async()=>{const {peer,channel}=await ready();const p=channel.request('cursor',{},sig());peer.feed({v:1,id:'1',op:'cursor',value:{marker:'exact'}});assert.equal((await p).marker,'exact');assert.equal(channel.stats().inflight,0);await channel.close()});
test('aborted-correlation-retained-until-owner-reply',async()=>{const {peer,channel}=await ready(),ac=new AbortController();const p=channel.request('wait',{},ac.signal);ac.abort();await assert.rejects(p,e=>e.code==='CANCELLED');assert.equal(channel.stats().inflight,1);const last=JSON.parse(peer.writes.at(-1).subarray(4));assert.equal(last.cancel,'1');peer.feed({v:1,id:'1',op:'wait',error:'HOST_REQUEST_CANCELLED'});await new Promise(r=>setImmediate(r));assert.equal(channel.stats().inflight,0);await channel.close()});
test('timeout-is-not-a-success-response',async()=>{const {peer,channel}=setup({requestTimeoutMs:15});peer.feed(hello());await channel.ready;await assert.rejects(channel.request('ack',{},sig()),e=>e.code==='HOST_REQUEST_TIMEOUT');await channel.close()});
test('oversize-request-does-not-grow-queue',async()=>{const {peer,channel}=await ready();await assert.rejects(channel.request('open',{x:'a'.repeat(70000)},sig()));assert.equal(peer.writes.length,0);await channel.close()});
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));process.exit(0)}
try{Channel=(await import(pathToFileURL(path.join(ROOT,'product/wp10/node/channel.mjs')))).ConnectedEventChannel}catch{}
const cases=[];for(const t of tests){try{await t.fn();cases.push({id:t.id,status:'PASS'});console.log('PASS',t.id)}catch(e){cases.push({id:t.id,status:'FAIL'});console.error('FAIL',t.id,e)}}
if(process.env.HARNESS_RESULT_PATH)fs.writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));process.exitCode=cases.every(x=>x.status==='PASS')?0:1;
