/** Actual Node/Python processes, private descriptors and SQLite restarts. */
import assert from 'node:assert/strict';
import fs from 'node:fs';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';
import path from 'node:path';import {pathToFileURL} from 'node:url';
import {start,publication,operation} from './command_integration.mjs';
const ROOT=process.env.PAR_ROOT||process.cwd(),tests=[];let lib;
const test=(id,fn)=>tests.push({id:'event-client.integration.'+id,fn});
const tick=()=>new Promise(r=>setImmediate(r));
async function run(fn){const root=mkdtempSync(path.join(tmpdir(),'par-client-')),workers=[],clients=[],extra=[];
 const create=async(mode='normal',different=false)=>{const dir=different?mkdtempSync(path.join(tmpdir(),'par-other-client-')):root;if(different)extra.push(dir);const w=await start(dir,mode);workers.push(w);return w};
 const bind=w=>{assert.equal(typeof lib.EventCommandClient,'function','lifecycle absent');const x=new lib.EventCommandClient(w.info.commandContext,{requestTimeoutMs:3000});clients.push(x);x.rebind(w.commandChannel,w.hello.context,w.hello.hostId);return x};
 try{await fn(create,bind,clients)}finally{for(const x of clients){x.close();await x.waitForCleanup()}for(const w of workers)await w.stop();for(const dir of [root,...extra])rmSync(dir,{recursive:true,force:true})}}
test('publish-inquire-and-projection-never-ack-subscription',()=>run(async(create,bind)=>{const w=await create(),x=bind(w);const s=await lib.EventSubscription.connect(w.port,w.info.subscriptionContext);const p=s.next();const result=await x.publish(publication());const batch=(await p).value;assert.equal(result.kind,'local-committed');assert.equal(batch.events[0].eventId,result.eventId);assert.equal(s.lastCursor.position,'0');await x.inquire(operation);assert.equal(s.lastCursor.position,'0');assert.equal(x.view.sharedCommit,false);assert.equal(x.view.remoteProtection,false);await batch.ack();assert.equal(s.lastCursor.position,'1');await s.close();x.close();await x.waitForCleanup();await w.stop();assert.equal(w.ended.stats.commands.channels,0);assert.equal(w.ended.stats.commands.requests,0);assert.equal(w.ended.stats.subscriptions.channels,0)}));
test('commit-sigkill-rebind-original-inquiry-without-replay',()=>run(async(create,bind)=>{let w=await create('kill-commit');const x=bind(w);assert.equal((await x.publish(publication())).kind,'outcome-unknown');assert.equal((await w.exit).signal,'SIGKILL');const old=w.hello.hostId;await w.stop();w=await create();assert.notEqual(w.hello.hostId,old);x.rebind(w.commandChannel,w.hello.context,w.hello.hostId);assert.equal(x.current.requiresInquiry,true);assert.equal(w.info.journal.events,1);assert.equal(w.info.journal.nonces,1);const r=await x.inquire(operation);assert.equal(r.kind,'local-committed');assert.equal(r.operationId,operation);assert.equal(x.current.requiresInquiry,false);x.close();await x.waitForCleanup();await w.stop();assert.equal(w.ended.journal.events,1);assert.equal(w.ended.journal.nonces,1)}));
test('nonce-sigkill-not-found-cannot-trigger-republication',()=>run(async(create,bind)=>{let w=await create('kill-nonce');const x=bind(w);await x.publish(publication());assert.equal((await w.exit).signal,'SIGKILL');await w.stop();w=await create();x.rebind(w.commandChannel,w.hello.context,w.hello.hostId);assert.equal((await x.inquire(operation)).kind,'not-found-local');assert.equal(x.view.canPublish,false);assert.equal((await x.publish(publication())).code,'CLIENT_INQUIRY_REQUIRED');assert.equal((await x.publish({...publication(),operationId:'ab'.repeat(16)})).code,'CLIENT_INQUIRY_REQUIRED');x.close();await x.waitForCleanup();await w.stop();assert.equal(w.ended.journal.events,0);assert.equal(w.ended.journal.nonces,1)}));
test('precommit-sigkill-reconciliation-keeps-reserved-nonce',()=>run(async(create,bind)=>{let w=await create('kill-before-commit');const x=bind(w);await x.publish(publication());assert.equal((await w.exit).signal,'SIGKILL');await w.stop();w=await create();x.rebind(w.commandChannel,w.hello.context,w.hello.hostId);assert.equal((await x.inquire(operation)).kind,'not-found-local');assert.equal(w.info.journal.nonces,1);assert.equal(w.info.journal.events,0);assert.equal(x.current.requiresInquiry,true)}));
test('commit-error-is-reconciled-with-local-receipt-only',()=>run(async(create,bind)=>{let w=await create('commit-error');const x=bind(w);assert.equal((await x.publish(publication())).kind,'outcome-unknown');await w.stop();w=await create();x.rebind(w.commandChannel,w.hello.context,w.hello.hostId);assert.equal((await x.inquire(operation)).kind,'local-committed');assert.equal(x.view.localReceipt.sequence,'1');assert.equal(x.view.remoteProtection,false);assert.equal(x.view.sharedCommit,false)}));
test('fresh-client-can-restore-caller-retained-original-input',()=>run(async(create,bind,clients)=>{let w=await create('kill-commit'),x=bind(w);const retained=publication();await x.publish(retained);x.close();await x.waitForCleanup();await w.stop();w=await create();x=new lib.EventCommandClient(w.info.commandContext);clients.push(x);x.restoreUnknown(retained);assert.equal(x.current.connection,'unbound');x.rebind(w.commandChannel,w.hello.context,w.hello.hostId);assert.equal((await x.inquire(operation)).sequence,'1');assert.equal(w.info.journal.events,1)}));
test('different-real-journal-generation-cannot-rebind',()=>run(async(create,bind)=>{const w=await create(),x=bind(w),other=await create('normal',true);assert.notEqual(w.info.commandContext.journalGeneration,other.info.commandContext.journalGeneration);assert.throws(()=>x.rebind(other.commandChannel,other.hello.context,other.hello.hostId),e=>e.code==='CLIENT_CONTEXT_MISMATCH');assert.equal(other.commandChannel.stats().closed,false);assert.equal((await x.publish(publication())).kind,'local-committed');assert.equal(x.current.hostId,w.hello.hostId)}));
test('changed-owner-grant-needs-a-separate-explicit-client',()=>run(async(create,bind,clients)=>{let w=await create();const x=bind(w);await x.publish(publication());x.close();await x.waitForCleanup();await w.stop();w=await create('inquire-only');const old=new lib.EventCommandClient({...w.info.commandContext,authority:'owner-publish'});clients.push(old);old.restoreUnknown(publication());assert.throws(()=>old.rebind(w.commandChannel,w.hello.context,w.hello.hostId),e=>e.code==='CLIENT_CONTEXT_MISMATCH');const read=bind(w);read.restoreUnknown(publication());assert.equal(read.view.canPublish,false);assert.equal((await read.inquire(operation)).kind,'local-committed');assert.equal((await read.publish(publication())).code,'COMMAND_NOT_AUTHORIZED')}));
test('killed-inquiry-host-is-unavailable-not-absence',()=>run(async(create,bind)=>{const w=await create(),x=bind(w);x.restoreUnknown(publication());w.child.kill('SIGKILL');await w.exit;const r=await x.inquire(operation);assert.equal(r.code,'INQUIRY_UNAVAILABLE');assert.equal(x.current.operation.kind,'inquiry-failed');assert.equal(x.current.requiresInquiry,true)}));
test('cleanup-detaches-real-stream-read-listeners',()=>run(async(create,bind)=>{
 const w=await create(),x=bind(w);
 // Channel construction follows child_process/socket internals; its handlers are
 // last in this controlled fixture. Do not remove Node's onReadableStreamEnd or
 // child_process maybeClose handlers in the name of application cleanup.
 const owned=Object.fromEntries(['data','end','close'].map(event=>[event,w.child.stdio[3].rawListeners(event).at(-1)]));
 const before=Object.fromEntries(['data','end','close'].map(event=>[event,w.child.stdio[3].rawListeners(event)]));
 await x.publish(publication());x.close();await x.waitForCleanup();await tick();
 assert.equal(w.commandChannel.stats().closed,true);assert.equal(w.commandChannel.stats().inflight,0);
 for(const event of ['data','end','close']){
  assert.ok(owned[event]);assert.ok(!w.child.stdio[3].rawListeners(event).includes(owned[event]));
  assert.deepEqual(w.child.stdio[3].rawListeners(event),before[event].filter(f=>f!==owned[event]));
 }
 assert.equal(x.current.cleanup.failed,false);
}));
test('client-close-does-not-ack-or-delete-committed-event',()=>run(async(create,bind)=>{let w=await create();const x=bind(w);await x.publish(publication());x.close();await x.waitForCleanup();await w.stop();w=await create();const s=await lib.EventSubscription.connect(w.port,w.info.subscriptionContext);assert.equal(s.lastCursor.position,'0');assert.equal((await s.poll()).events[0].operationId,operation);await s.close();assert.equal(w.info.journal.events,1)}));
test('owner-current-membership-still-rejects-reader-publish',()=>run(async(create,bind)=>{const w=await create('reader'),x=bind(w);const r=await x.publish(publication());assert.equal(r.code,'NOT_AUTHORIZED');assert.equal(x.current.requiresInquiry,false);x.close();await x.waitForCleanup();await w.stop();assert.equal(w.ended.journal.nonces,0);assert.equal(w.ended.journal.events,0)}));
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));process.exit(0)}
lib=await import(pathToFileURL(path.join(process.env.PAR_SDK_BUILD||path.join(ROOT,'product/wp10/lib'),'index.js')));
const cases=[];for(const t of tests){try{await t.fn();cases.push({id:t.id,status:'PASS'});console.log('PASS',t.id)}catch(e){cases.push({id:t.id,status:'FAIL'});console.error('FAIL',t.id,e)}}
if(process.env.HARNESS_RESULT_PATH)fs.writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));process.exitCode=cases.every(x=>x.status==='PASS')?0:1;
