/** Reference application status boundary; no browser/renderer execution claimed. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const ROOT=process.env.PAR_ROOT||process.cwd(),tests=[];let sdk,ui;
const test=(id,fn)=>tests.push({id:'event-client.view.'+id,fn});
const op='01'.repeat(16),host='66'.repeat(16);
const context=()=>({protocol:'par-local-event-commands-0040',appId:'test.app',spaceId:'11'.repeat(32),streamId:'22'.repeat(32),epoch:'1',schema:{body:'text'},schemaDigest:'33'.repeat(32),issuer:'44'.repeat(32),journalGeneration:'55'.repeat(32),authority:'owner-publish'});
const input=()=>({operationId:op,payload:{body:{kind:'text',value:'secret draft-like body'}},parents:[]});
const reply=kind=>({kind,context:context(),hostId:host,operationId:op,...(kind==='local-committed'?{sequence:'18446744073709551615',eventId:'77'.repeat(32),replicated:false,cancellationRequested:false}:kind==='rejected'?{code:'NOT_AUTHORIZED'}:{})});
function setup(fn=async()=>reply('local-committed')){const client=new sdk.EventCommandClient(context()),calls=[];client.rebind({request(...args){calls.push(args);return fn(...args)},close(){}},context(),host);return {client,calls}}
function view(client,expected=context(),locale='ja'){assert.equal(typeof ui.presentLocalEventClient,'function','reference app event status boundary is missing');return ui.presentLocalEventClient(client,expected,locale)}
test('status-is-separate-from-shared-note-and-private-draft',async()=>{const {client,calls}=setup();await client.publish(input());const panel=view(client);assert.equal(panel.sharedCommit,false);assert.equal(panel.remoteProtection,false);assert.equal(panel.productQualified,false);assert.equal(panel.eventSequence,'18446744073709551615');assert.equal(panel.operationId,op);for(const k of ['document','draft','payload','protection'])assert.equal(Object.hasOwn(panel,k),false);assert.equal(calls.length,1);client.close()});
test('display-does-not-emit-any-command',()=>{const {client,calls}=setup();view(client);view(client);assert.equal(calls.length,0);client.close()});
test('wrong-context-is-rejected-before-display',()=>{const {client}=setup();assert.throws(()=>view(client,{...context(),streamId:'ab'.repeat(32)}),e=>e.code==='LOCAL_EVENT_CONTEXT_MISMATCH');client.close()});
test('unknown-is-not-failure-or-unsaved',()=>{const {client}=setup();client.restoreUnknown(input());const panel=view(client);assert.equal(panel.outcome,'outcome-unknown');assert.equal(panel.controls.publish,false);assert.equal(panel.controls.inquire,true);assert.ok(panel.message.includes('不明'));assert.ok(!JSON.stringify(panel).includes('secret draft-like body'));client.close()});
test('not-found-asks-for-no-automatic-replay',async()=>{const {client}=setup(async()=>reply('not-found-local'));client.restoreUnknown(input());await client.inquire(op);const panel=view(client);assert.equal(panel.outcome,'not-found-local');assert.equal(panel.controls.publish,false);assert.ok(panel.message.includes('再送'));assert.equal(panel.automaticRetry,false);client.close()});
test('inquiry-failure-is-distinct-from-local-absence',async()=>{const {client}=setup(async()=>{throw Error('lost')});client.restoreUnknown(input());await client.inquire(op);const panel=view(client);assert.equal(panel.outcome,'inquiry-failed');assert.equal(panel.controls.rebind,true);assert.equal(panel.controls.inquire,false);assert.ok(panel.message.includes('不在'));client.close()});
test('closed-client-does-not-show-actionable-controls',async()=>{const {client}=setup();await client.publish(input());client.close();const panel=view(client);assert.equal(panel.connection,'closed');assert.deepEqual(panel.controls,{publish:false,inquire:false,rebind:false});assert.equal(panel.sharedCommit,false);assert.equal(panel.localReceiptPreviouslyObserved,true)});
test('japanese-and-english-copy-explain-local-only-receipt',async()=>{const {client}=setup();await client.publish(input());const ja=view(client),en=view(client,context(),'en');assert.notEqual(ja.message,en.message);assert.ok(en.message.includes('local event'));assert.ok(en.message.includes('shared document'));assert.ok(ja.message.includes('共有文書'));client.close()});
test('panel-and-nested-control-state-are-immutable',()=>{const {client}=setup();const p=view(client);assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.controls));assert.ok(Object.isFrozen(p.scope));client.close()});
test('unknown-locale-is-refused',()=>{const {client}=setup();assert.throws(()=>view(client,context(),'fr'),e=>e.code==='INVALID_INPUT');client.close()});
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));process.exit(0)}
sdk=await import(pathToFileURL(path.join(ROOT,'product/wp10/lib/index.js')));ui=await import(pathToFileURL(path.join(ROOT,'product/wp11/lib/index.js')));
const cases=[];for(const t of tests){try{await t.fn();cases.push({id:t.id,status:'PASS'});console.log('PASS',t.id)}catch(e){cases.push({id:t.id,status:'FAIL'});console.error('FAIL',t.id,e)}}
if(process.env.HARNESS_RESULT_PATH)fs.writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));process.exitCode=cases.every(x=>x.status==='PASS')?0:1;
