/** State-machine opponents; real storage is exercised separately by integration. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const ROOT=process.env.PAR_ROOT||process.cwd(),tests=[];
const test=(id,fn)=>tests.push({id:'event-client.node.'+id,fn});let lib;
const op='01'.repeat(16),host='66'.repeat(16),host2='88'.repeat(16);
const context=()=>({protocol:'par-local-event-commands-0040',appId:'test.app',spaceId:'11'.repeat(32),streamId:'22'.repeat(32),epoch:'18446744073709551615',schema:{body:'text',count:'uint64'},schemaDigest:'33'.repeat(32),issuer:'44'.repeat(32),journalGeneration:'55'.repeat(32),authority:'owner-publish'});
const input=()=>({operationId:op,payload:{body:{kind:'text',value:'private never projected'},count:{kind:'uint64',value:'18446744073709551615'}},parents:[]});
const reply=(kind='local-committed',h=host,ctx=context(),id=op)=>({context:ctx,hostId:h,operationId:id,kind,...(kind==='local-committed'?{sequence:'18446744073709551615',eventId:'77'.repeat(32),replicated:false,cancellationRequested:false}:kind==='rejected'?{code:'NOT_AUTHORIZED'}:{})});
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const tick=()=>new Promise(r=>setImmediate(r));
function channel(fn=async()=>reply(),closeFn=()=>{}){const c={calls:[],closes:0,request(...args){c.calls.push(args);return fn(...args)},close(){c.closes++;return closeFn()}};return c}
function client(opts={}){assert.equal(typeof lib.EventCommandClient,'function','explicit lifecycle is not implemented');return new lib.EventCommandClient(context(),opts)}
function bound(c=channel(),opts={}){const x=client(opts);x.rebind(c,context(),host);return {x,c}}
const code=c=>e=>e?.code===c;
async function gone(x,c){x.close();await x.waitForCleanup();assert.equal(c.closes,1);assert.equal(x.current.cleanup.pending,0)}
test('initial-unbound-snapshot-is-immutable',()=>{const x=client();assert.equal(x.current.connection,'unbound');assert.equal(x.current.operation.kind,'idle');assert.equal(x.current.requiresInquiry,false);assert.ok(Object.isFrozen(x.current));assert.ok(Object.isFrozen(x.current.context.schema));assert.equal(x.view.canPublish,false)});
test('bind-is-explicit-and-performs-no-command',async()=>{const {x,c}=bound();assert.equal(x.current.connection,'connected');assert.equal(c.calls.length,0);assert.equal(x.view.canPublish,true);await gone(x,c)});
test('publish-without-bind-does-not-create-pending-operation',async()=>{const x=client();assert.equal((await x.publish(input())).code,'CLIENT_REBIND_REQUIRED');assert.equal(x.current.operation.kind,'idle')});
test('committed-publish-preserves-exact-integer-and-local-claim',async()=>{const {x,c}=bound();const r=await x.publish(input());assert.equal(r.sequence,'18446744073709551615');assert.equal(x.current.operation.kind,'local-committed');assert.equal(x.current.knownCommit.eventId,r.eventId);assert.equal(x.current.requiresInquiry,false);assert.equal(x.view.sharedCommit,false);assert.equal(x.view.remoteProtection,false);await gone(x,c)});
test('snapshot-and-view-never-expose-payload-or-parent',async()=>{const {x,c}=bound();await x.publish(input());const raw=JSON.stringify([x.current,x.view]);assert.ok(!raw.includes('private never projected'));assert.ok(!raw.includes('parents'));assert.ok(!raw.includes('payload'));assert.equal(x.view.operationId,op);await gone(x,c)});
test('before-send-abort-is-zero-io-and-no-pending-state',async()=>{const {x,c}=bound(),a=new AbortController();a.abort();assert.equal((await x.publish(input(),{signal:a.signal})).phase,'before-send');assert.equal(c.calls.length,0);assert.equal(x.current.operation.kind,'idle');await gone(x,c)});
test('after-send-abort-is-unknown-and-releases-channel',async()=>{const d=defer(),{x,c}=bound(channel(()=>d.promise)),a=new AbortController();const p=x.publish(input(),{signal:a.signal});a.abort();assert.equal((await p).kind,'outcome-unknown');assert.equal(x.current.connection,'rebind-required');assert.equal(x.current.requiresInquiry,true);assert.equal(c.closes,1);d.resolve(reply());await tick();assert.equal(x.current.operation.kind,'outcome-unknown');await gone(x,c)});
test('unknown-never-retries-old-or-new-operation',async()=>{const {x,c}=bound(channel(async()=>{throw Error('loss')}));await x.publish(input());assert.equal((await x.publish(input())).code,'CLIENT_INQUIRY_REQUIRED');assert.equal((await x.publish({...input(),operationId:'ab'.repeat(16)})).code,'CLIENT_INQUIRY_REQUIRED');assert.equal(c.calls.length,1);await gone(x,c)});
test('restore-original-input-is-zero-io-and-deep-copy',async()=>{const {x,c}=bound(channel(async()=>reply('not-found-local'))),a=input();x.restoreUnknown(a);a.payload.body.value='changed';assert.equal(c.calls.length,0);assert.equal(x.current.requiresInquiry,true);assert.equal((await x.publish(a)).code,'CLIENT_OPERATION_CONFLICT');assert.equal((await x.inquire(op)).kind,'not-found-local');assert.equal(c.calls[0][1].operationId,op);await gone(x,c)});
test('restore-cannot-replace-existing-unresolved-operation',()=>{const x=client();x.restoreUnknown(input());assert.throws(()=>x.restoreUnknown({...input(),operationId:'ab'.repeat(16)}),code('CLIENT_OPERATION_RETAINED'));assert.equal(x.current.operation.operationId,op);x.close()});
test('inquiry-requires-exact-retained-original-id',async()=>{const {x,c}=bound();x.restoreUnknown(input());assert.equal((await x.inquire('ab'.repeat(16))).code,'CLIENT_OPERATION_MISMATCH');assert.equal(c.calls.length,0);await gone(x,c)});
test('inquiry-without-retained-input-is-refused',async()=>{const {x,c}=bound();assert.equal((await x.inquire(op)).code,'CLIENT_NO_OPERATION');assert.equal(c.calls.length,0);await gone(x,c)});
test('rebind-does-not-automatically-inquire-or-resend',async()=>{const {x,c}=bound(channel(async()=>{throw Error()}));await x.publish(input());const c2=channel(async()=>reply('local-committed',host2));x.rebind(c2,context(),host2);assert.equal(c2.calls.length,0);assert.equal(x.current.requiresInquiry,true);assert.equal(x.view.canPublish,false);assert.equal(x.view.canInquire,true);assert.equal((await x.inquire(op)).kind,'local-committed');assert.equal(c2.calls[0][0],'inquire');assert.equal(x.current.requiresInquiry,false);await gone(x,c2);assert.equal(c.closes,1)});
test('not-found-is-observation-not-replay-permission',async()=>{const {x,c}=bound(channel(async()=>reply('not-found-local')));x.restoreUnknown(input());assert.equal((await x.inquire(op)).kind,'not-found-local');assert.equal(x.current.operation.kind,'not-found-local');assert.equal(x.current.requiresInquiry,true);assert.equal(x.view.canPublish,false);assert.equal((await x.publish(input())).code,'CLIENT_INQUIRY_REQUIRED');assert.equal(c.calls.length,1);await gone(x,c)});
test('inquiry-failure-is-never-absence',async()=>{const {x,c}=bound(channel(async()=>{throw Error('not found secret')}));x.restoreUnknown(input());const r=await x.inquire(op);assert.equal(r.code,'INQUIRY_UNAVAILABLE');assert.equal(x.current.operation.kind,'inquiry-failed');assert.equal(x.current.connection,'rebind-required');assert.equal(x.current.requiresInquiry,true);assert.ok(!JSON.stringify(x.current).includes('secret'));await gone(x,c)});
test('inquiry-abort-before-send-retains-unknown-with-no-io',async()=>{const {x,c}=bound(),a=new AbortController();x.restoreUnknown(input());a.abort();assert.equal((await x.inquire(op,{signal:a.signal})).phase,'before-send');assert.equal(x.current.operation.kind,'outcome-unknown');assert.equal(c.calls.length,0);await gone(x,c)});
test('inquiry-abort-after-send-is-failed-not-absent',async()=>{const {x,c}=bound(channel(()=>new Promise(()=>{}))),a=new AbortController();x.restoreUnknown(input());const p=x.inquire(op,{signal:a.signal});a.abort();assert.equal((await p).code,'INQUIRY_UNAVAILABLE');assert.equal(x.current.operation.kind,'inquiry-failed');assert.equal(x.current.requiresInquiry,true);await gone(x,c)});
test('old-publish-after-rebind-cannot-overwrite-new-inquiry',async()=>{const d=defer(),{x,c}=bound(channel(()=>d.promise));const p=x.publish(input());const c2=channel(async()=>reply('local-committed',host2));x.rebind(c2,context(),host2);const q=await x.inquire(op);d.resolve({...reply(),eventId:'ff'.repeat(32)});assert.equal((await p).kind,'outcome-unknown');await tick();assert.equal(x.current.knownCommit.eventId,q.eventId);assert.equal(x.current.operation.kind,'local-committed');assert.equal(x.current.hostId,host2);await gone(x,c2);assert.equal(c.closes,1)});
test('same-host-id-new-binding-still-fences-old-completion',async()=>{const d=defer(),{x,c}=bound(channel(()=>d.promise));const p=x.publish(input()),g=x.current.bindingGeneration,c2=channel();x.rebind(c2,context(),host);assert.ok(BigInt(x.current.bindingGeneration)>BigInt(g));await x.inquire(op);d.resolve({...reply(),sequence:'1'});await p;await tick();assert.equal(x.current.knownCommit.sequence,'18446744073709551615');await gone(x,c2)});
test('old-inquiry-after-rebind-cannot-install-absence',async()=>{const d=defer(),{x}=bound(channel(()=>d.promise));x.restoreUnknown(input());const p=x.inquire(op),c2=channel(async()=>reply('local-committed',host2));x.rebind(c2,context(),host2);await x.inquire(op);d.resolve(reply('not-found-local'));assert.equal((await p).code,'CLIENT_SUPERSEDED');assert.equal(x.current.operation.kind,'local-committed');await gone(x,c2)});
test('close-during-publish-is-terminal-and-unknown',async()=>{const d=defer(),{x,c}=bound(channel(()=>d.promise));const p=x.publish(input());x.close();d.resolve(reply());assert.equal((await p).kind,'outcome-unknown');assert.equal(x.current.connection,'closed');assert.equal(x.current.operation.kind,'outcome-unknown');assert.equal((await x.publish(input())).code,'CLIENT_CLOSED');await gone(x,c)});
test('close-during-inquiry-does-not-turn-late-receipt-into-current',async()=>{const d=defer(),{x,c}=bound(channel(()=>d.promise));x.restoreUnknown(input());const p=x.inquire(op);x.close();d.resolve(reply());assert.equal((await p).code,'CLIENT_SUPERSEDED');assert.equal(x.current.connection,'closed');assert.equal(x.current.knownCommit,null);await gone(x,c)});
test('close-is-idempotent-and-rejects-rebind-with-caller-ownership',async()=>{const {x,c}=bound();x.close();x.close();const c2=channel();assert.throws(()=>x.rebind(c2,context(),host2),code('CLIENT_CLOSED'));assert.equal(c2.closes,0);assert.equal(c.closes,1);await x.waitForCleanup()});
test('same-channel-object-cannot-be-rebound',async()=>{const {x,c}=bound();assert.throws(()=>x.rebind(c,context(),host),code('CLIENT_CHANNEL_REUSED'));assert.equal(c.closes,0);await gone(x,c)});
for(const [field,value] of [['appId','other.app'],['streamId','ab'.repeat(32)],['spaceId','ab'.repeat(32)],['epoch','1'],['issuer','ab'.repeat(32)],['journalGeneration','ab'.repeat(32)],['authority','inquire-only'],['schemaDigest','ab'.repeat(32)],['schema',{body:'text',count:'int64'}]]){
 test('rebind-rejects-changed-'+field+'-without-displacing-old',async()=>{const {x,c}=bound(),c2=channel(),g=x.current.bindingGeneration;assert.throws(()=>x.rebind(c2,{...context(),[field]:value},host2),code('CLIENT_CONTEXT_MISMATCH'));assert.equal(c2.closes,0);assert.equal(c.closes,0);assert.equal(x.current.bindingGeneration,g);assert.equal((await x.publish(input())).kind,'local-committed');await gone(x,c)})
}
test('one-inflight-operation-and-concurrent-call-does-not-change-state',async()=>{const d=defer(),{x,c}=bound(channel(()=>d.promise));const p=x.publish(input()),r=x.current.revision;assert.equal((await x.inquire(op)).code,'CLIENT_BUSY');assert.equal((await x.publish(input())).code,'CLIENT_BUSY');assert.equal(x.current.revision,r);assert.equal(c.calls.length,1);d.resolve(reply());await p;await gone(x,c)});
test('same-operation-different-input-refused-locally-after-commit',async()=>{const {x,c}=bound();await x.publish(input());const changed=input();changed.payload.body.value='different';assert.equal((await x.publish(changed)).code,'CLIENT_OPERATION_CONFLICT');assert.equal(c.calls.length,1);await gone(x,c)});
test('new-operation-is-allowed-only-after-settled-result',async()=>{const c=channel(async(_op,a)=>reply('local-committed',host,context(),a.operationId)),{x}=bound(c);await x.publish(input());const id='ab'.repeat(16);assert.equal((await x.publish({...input(),operationId:id})).operationId,id);assert.equal(x.current.operation.operationId,id);assert.equal(c.calls.length,2);await gone(x,c)});
test('owner-rejection-is-not-a-reconnection-failure',async()=>{const {x,c}=bound(channel(async()=>reply('rejected')));assert.equal((await x.publish(input())).kind,'rejected');assert.equal(x.current.requiresInquiry,false);assert.equal(x.current.connection,'connected');await gone(x,c)});
test('owner-cancel-before-commit-is-settled',async()=>{const c=channel(async()=>({...reply('cancelled'),phase:'before-commit'})),{x}=bound(c);assert.equal((await x.publish(input())).phase,'before-commit');assert.equal(x.current.requiresInquiry,false);await gone(x,c)});
test('prior-receipt-is-not-erased-by-contradictory-absence',async()=>{let count=0;const {x,c}=bound(channel(async()=>reply(++count===1?'local-committed':'not-found-local')));await x.publish(input());assert.equal((await x.inquire(op)).code,'CLIENT_OBSERVATION_CONFLICT');assert.equal(x.current.knownCommit.eventId,'77'.repeat(32));assert.equal(x.current.operation.kind,'inquiry-failed');assert.equal(x.current.connection,'rebind-required');await gone(x,c)});
test('prior-receipt-cannot-change-event-id-or-sequence',async()=>{let count=0;const {x,c}=bound(channel(async()=>({...reply(),sequence:++count===1?'18446744073709551615':'1'})));await x.publish(input());assert.equal((await x.inquire(op)).code,'CLIENT_OBSERVATION_CONFLICT');assert.equal(x.current.knownCommit.sequence,'18446744073709551615');await gone(x,c)});
test('timeout-on-noncooperative-port-is-bounded-unknown',async()=>{const {x,c}=bound(channel(()=>new Promise(()=>{})),{requestTimeoutMs:15});assert.equal((await x.publish(input())).kind,'outcome-unknown');assert.equal(c.calls.length,1);await gone(x,c)});
test('external-abort-listener-removed-after-settlement',async()=>{const {x,c}=bound(),ac=new AbortController(),s=ac.signal;let adds=0,removes=0;const add=s.addEventListener.bind(s),remove=s.removeEventListener.bind(s);s.addEventListener=(...a)=>{adds++;return add(...a)};s.removeEventListener=(...a)=>{removes++;return remove(...a)};await x.publish(input(),{signal:s});assert.ok(adds>0);assert.equal(adds,removes);await gone(x,c)});
test('snapshot-revision-increases-and-old-object-does-not-change',async()=>{const {x,c}=bound(),old=x.current;await x.publish(input());assert.ok(BigInt(x.current.revision)>BigInt(old.revision));assert.equal(old.operation.kind,'idle');await gone(x,c)});
test('invalid-input-and-accessors-make-zero-io',async()=>{const {x,c}=bound();const a=input();let reads=0;Object.defineProperty(a.payload.body,'value',{get(){reads++;return 'x'},enumerable:true});await assert.rejects(x.publish(a),code('COMMAND_INPUT_INVALID'));assert.throws(()=>x.restoreUnknown(a),code('COMMAND_INPUT_INVALID'));assert.equal(reads,0);assert.equal(c.calls.length,0);assert.equal(x.current.operation.kind,'idle');await gone(x,c)});
test('invalid-lifecycle-options-refused-before-bind',()=>{for(const opts of [{requestTimeoutMs:0},{cleanupTimeoutMs:0},{cleanupTimeoutMs:Infinity},{unknown:1}])assert.throws(()=>client(opts),code('INVALID_OPTIONS'))});
test('invalid-signal-does-not-retain-or-send-operation',async()=>{const {x,c}=bound();await assert.rejects(x.publish(input(),{signal:{}}),code('INVALID_OPTIONS'));assert.equal(x.current.operation.kind,'idle');assert.equal(c.calls.length,0);await gone(x,c)});
test('cleanup-rejection-is-observed-and-latches-admission-closed',async()=>{const errors=[],capture=e=>errors.push(e);process.on('unhandledRejection',capture);try{const {x,c}=bound(channel(async()=>reply(),()=>Promise.reject(Error('private close failure'))));x.close();await x.waitForCleanup();await tick();assert.equal(x.current.cleanup.failed,true);assert.equal(errors.length,0);assert.ok(!JSON.stringify(x.current).includes('private close failure'));assert.equal(c.closes,1)}finally{process.off('unhandledRejection',capture)}});
test('noncooperative-cleanup-times-out-with-no-false-release-claim',async()=>{const {x,c}=bound(channel(async()=>reply(),()=>new Promise(()=>{})),{cleanupTimeoutMs:15});const c2=channel();x.rebind(c2,context(),host2);await x.waitForCleanup();assert.equal(x.current.cleanup.failed,true);assert.equal(x.current.cleanup.pending,0);const c3=channel();assert.throws(()=>x.rebind(c3,context(),host),code('CLIENT_CLEANUP_FAILED'));assert.equal(c3.closes,0);x.close();await x.waitForCleanup();assert.equal(c.closes,1)});
test('pending-cleanup-admission-is-bounded',async()=>{const x=client({cleanupTimeoutMs:1000}),closers=[];let c;for(let i=0;i<5;i++){const d=defer();closers.push(d);c=channel(async()=>reply(),()=>d.promise);x.rebind(c,context(),host)}const c6=channel();assert.throws(()=>x.rebind(c6,context(),host),code('CLIENT_CLEANUP_PENDING'));assert.equal(c6.closes,0);assert.equal(x.current.cleanup.pending,4);for(const d of closers)d.resolve();await x.waitForCleanup();x.close();await x.waitForCleanup();assert.equal(x.current.cleanup.failed,false)});
test('synchronous-port-throw-has-no-unhandled-rejection',async()=>{const errors=[],capture=e=>errors.push(e);process.on('unhandledRejection',capture);try{const {x,c}=bound(channel(()=>{throw Error('loss')}));assert.equal((await x.publish(input())).kind,'outcome-unknown');await gone(x,c);await tick();assert.equal(errors.length,0)}finally{process.off('unhandledRejection',capture)}});
test('null-options-is-stable-input-error-not-typeerror',async()=>{const {x,c}=bound();await assert.rejects(x.publish(input(),null),code('INVALID_OPTIONS'));assert.equal(c.calls.length,0);await gone(x,c)});
test('inherited-abort-signal-cannot-be-silently-ignored',async()=>{const {x,c}=bound(),a=new AbortController();a.abort();await assert.rejects(x.publish(input(),Object.create({signal:a.signal})),code('INVALID_OPTIONS'));assert.equal(c.calls.length,0);assert.equal(x.current.operation.kind,'idle');await gone(x,c)});
test('close-detaches-caller-abort-listener-synchronously',async()=>{const {x,c}=bound(channel(()=>new Promise(()=>{}))),a=new AbortController(),s=a.signal;let live=0;const add=s.addEventListener.bind(s),remove=s.removeEventListener.bind(s);s.addEventListener=(...args)=>{live++;return add(...args)};s.removeEventListener=(...args)=>{live--;return remove(...args)};const p=x.publish(input(),{signal:s});assert.equal(live,1);x.close();assert.equal(live,0);await p;assert.equal(live,0);await gone(x,c)});
test('rebind-detaches-old-caller-abort-without-touching-successor',async()=>{const {x}=bound(channel(()=>new Promise(()=>{}))),a=new AbortController(),s=a.signal;let live=0;const add=s.addEventListener.bind(s),remove=s.removeEventListener.bind(s);s.addEventListener=(...args)=>{live++;return add(...args)};s.removeEventListener=(...args)=>{live--;return remove(...args)};const p=x.publish(input(),{signal:s}),c2=channel(async()=>reply('local-committed',host2));x.rebind(c2,context(),host2);assert.equal(live,0);a.abort();assert.equal((await x.inquire(op)).kind,'local-committed');await p;assert.equal(live,0);await gone(x,c2)});
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));process.exit(0)}
lib=await import(pathToFileURL(path.join(process.env.PAR_SDK_BUILD||path.join(ROOT,'product/wp10/lib'),'index.js')));
const cases=[];for(const t of tests){try{await t.fn();cases.push({id:t.id,status:'PASS'});console.log('PASS',t.id)}catch(e){cases.push({id:t.id,status:'FAIL'});console.error('FAIL',t.id,e)}}
if(process.env.HARNESS_RESULT_PATH)fs.writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));process.exitCode=cases.every(x=>x.status==='PASS')?0:1;
