import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import fs from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {createInterface} from 'node:readline';import {pathToFileURL} from 'node:url';
const ROOT=process.env.PAR_ROOT||process.cwd(),tests=[];const test=(id,fn)=>tests.push({id:'event-command.integration.'+id,fn});let lib,CommandChannel,SubscriptionChannel;
export const operation='01'.repeat(16);
export const publication=()=>({operationId:operation,payload:{body:{kind:'text',value:'private typed event'},count:{kind:'uint64',value:'18446744073709551615'},delta:{kind:'int64',value:'-9223372036854775808'},data:{kind:'bytes',value:'00ff'},ok:{kind:'bool',value:true}},parents:[]});
export async function start(root,mode='normal'){
 if(!lib)lib=await import(pathToFileURL(path.join(process.env.PAR_SDK_BUILD||path.join(ROOT,'product/wp10/lib'),'index.js')));
 if(!CommandChannel)CommandChannel=(await import(pathToFileURL(path.join(ROOT,'product/wp10/node/command-channel.mjs')))).ConnectedCommandChannel;
 if(!SubscriptionChannel)SubscriptionChannel=(await import(pathToFileURL(path.join(ROOT,'product/wp10/node/channel.mjs')))).ConnectedEventChannel;
 const child=spawn(process.env.PAR_PYTHON||'python3',['-I','-S','-B',path.join(ROOT,'tests/product/event-host/command_owner_process.py'),root,mode],{cwd:ROOT,stdio:['ignore','pipe','pipe','pipe','pipe']});
 let resolve,reject,info,ended,stderr='';const boot=new Promise((a,b)=>{resolve=a;reject=b});
 const reader=createInterface({input:child.stdout});reader.on('line',line=>{try{const r=JSON.parse(line);if(r.ready){info=r;resolve(r)}else if(r.ended)ended=r}catch(e){reject(e)}});
 child.stderr.on('data',b=>stderr=(stderr+b).slice(-8192));child.on('error',reject);
 const exit=new Promise(res=>child.once('exit',(code,signal)=>{reject(new Error('owner startup exited '+code+' '+signal+' '+stderr));res({code,signal})}));
 let timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('startup timeout '+stderr))},10000);
 try{await boot}finally{clearTimeout(timer)}
 assert.deepEqual(info.socket_families,[1,1]);
 const commandChannel=new CommandChannel(child.stdio[3],{expectedContext:info.commandContext,requestTimeoutMs:2500});
 const subscriptionChannel=new SubscriptionChannel(child.stdio[4],{expectedContext:info.subscriptionContext,requestTimeoutMs:2500});
 const [hello,subHello]=await Promise.all([commandChannel.ready,subscriptionChannel.ready]);assert.equal(hello.hostId,subHello.hostId);
 const commands=new lib.EventCommands(commandChannel,hello.context,hello.hostId,{requestTimeoutMs:3000});
 const port=new lib.GenerationEventPort(subscriptionChannel,subHello.hostId);
 async function stop(kill=false){
  if(kill&&child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');
  commands.close();await Promise.all([commandChannel.close(),subscriptionChannel.close()]);
  let timer;try{await Promise.race([exit,new Promise((_,j)=>{timer=setTimeout(()=>{child.kill('SIGKILL');j(new Error('cleanup timeout '+stderr))},5000)})])}
  finally{clearTimeout(timer);reader.close();for(const stream of child.stdio)stream?.destroy()}
 }
 return {child,commands,commandChannel,subscriptionChannel,port,info,hello,stop,exit,get ended(){return ended}};
}
async function run(fn){const root=mkdtempSync(path.join(tmpdir(),'par-command-')),workers=[];const create=async mode=>{const w=await start(root,mode);workers.push(w);return w};try{await fn(create,root)}finally{for(const w of workers)await w.stop();rmSync(root,{recursive:true,force:true})}}
test('publish-notifies-subscription-and-only-explicit-ack-advances',()=>run(async create=>{
 const w=await create();const s=await lib.EventSubscription.connect(w.port,w.info.subscriptionContext);assert.equal(await s.poll(),null);
 const waiting=s.next();const r=await w.commands.publish(publication());assert.equal(r.kind,'local-committed');assert.equal(r.replicated,false);
 const batch=(await waiting).value,event=batch.events[0];assert.equal(event.eventId,r.eventId);assert.equal(event.payload.count,18446744073709551615n);assert.equal(event.payload.delta,-9223372036854775808n);assert.equal(event.payload.data.hex,'00ff');assert.equal(event.payload.ok,true);
 assert.equal(s.lastCursor.position,'0');assert.deepEqual(await w.commands.inquire(operation),r);await batch.ack();assert.equal(s.lastCursor.position,'1');await s.close();await w.stop();
 assert.equal(w.ended.stats.commands.channels,0);assert.equal(w.ended.stats.subscriptions.channels,0);assert.equal(w.ended.stats.commands.requests,0);assert.ok(w.ended.storage_threads.length>0&&w.ended.storage_threads.every(x=>x===w.info.owner_thread));
}));
test('same-operation-input-is-idempotent-and-conflicting-input-refused',()=>run(async create=>{const w=await create();const a=await w.commands.publish(publication());assert.deepEqual(await w.commands.publish(publication()),a);const changed=publication();changed.payload.body.value='conflict';assert.equal((await w.commands.publish(changed)).code,'OPERATION_CONFLICT');await w.stop();assert.equal(w.ended.journal.events,1);assert.equal(w.ended.journal.nonces,1)}));
test('before-send-abort-has-no-nonce-no-event',()=>run(async create=>{const w=await create(),ac=new AbortController();ac.abort();assert.equal((await w.commands.publish(publication(),{signal:ac.signal})).phase,'before-send');await w.stop();assert.equal(w.ended.journal.events,0);assert.equal(w.ended.journal.nonces,0)}));
test('commit-sigkill-reconciles-by-original-operation-without-replay',()=>run(async create=>{let w=await create('kill-commit');const r=await w.commands.publish(publication());assert.equal(r.kind,'outcome-unknown');assert.equal(r.operationId,operation);assert.equal((await w.exit).signal,'SIGKILL');await w.stop();w=await create();const found=await w.commands.inquire(operation);assert.equal(found.kind,'local-committed');assert.equal(found.sequence,'1');assert.equal(w.info.journal.events,1);assert.equal(w.info.journal.nonces,1);const s=await lib.EventSubscription.connect(w.port,w.info.subscriptionContext);assert.equal(s.lastCursor.position,'0');assert.equal((await s.poll()).events[0].eventId,found.eventId);await s.close()}));
test('nonce-sigkill-keeps-reservation-and-never-auto-republishes',()=>run(async create=>{let w=await create('kill-nonce');assert.equal((await w.commands.publish(publication())).kind,'outcome-unknown');assert.equal((await w.exit).signal,'SIGKILL');await w.stop();w=await create();assert.equal((await w.commands.inquire(operation)).kind,'not-found-local');assert.equal(w.info.journal.events,0);assert.equal(w.info.journal.nonces,1);const r=await w.commands.publish(publication());assert.equal(r.kind,'local-committed');await w.stop();assert.equal(w.ended.journal.nonces,2);assert.equal(w.ended.journal.events,1)}));
test('owner-cancel-after-nonce-is-uncertain-remotely-and-absent-after-reopen',()=>run(async create=>{let w=await create('cancel-nonce');assert.equal((await w.commands.publish(publication())).kind,'outcome-unknown');await w.stop();assert.equal(w.ended.journal.nonces,1);assert.equal(w.ended.journal.events,0);w=await create();assert.equal((await w.commands.inquire(operation)).kind,'not-found-local');assert.equal(w.info.journal.nonces,1)}));
test('precommit-sigkill-rolls-back-event-not-nonce',()=>run(async create=>{let w=await create('kill-before-commit');assert.equal((await w.commands.publish(publication())).kind,'outcome-unknown');assert.equal((await w.exit).signal,'SIGKILL');await w.stop();w=await create();assert.equal((await w.commands.inquire(operation)).kind,'not-found-local');assert.equal(w.info.journal.nonces,1);assert.equal(w.info.journal.events,0)}));
test('postcommit-owner-error-is-unknown-then-found',()=>run(async create=>{let w=await create('commit-error');assert.equal((await w.commands.publish(publication())).kind,'outcome-unknown');await w.stop();w=await create();assert.equal((await w.commands.inquire(operation)).kind,'local-committed');assert.equal(w.info.journal.nonces,1)}));
test('inquiry-only-descriptor-refuses-bypassing-sdk-grant',()=>run(async create=>{const w=await create('inquire-only');const reply=await w.commandChannel.request('publish',{...publication(),context:w.info.commandContext},new AbortController().signal);assert.equal(reply.kind,'rejected');assert.equal(reply.code,'COMMAND_NOT_AUTHORIZED');await w.stop();assert.equal(w.ended.journal.nonces,0)}));
test('current-reader-membership-cannot-be-upgraded-by-command-grant',()=>run(async create=>{const w=await create('reader');assert.equal((await w.commands.publish(publication())).code,'NOT_AUTHORIZED');await w.stop();assert.equal(w.ended.journal.nonces,0)}));
test('wrong-stream-context-refused-before-reservation',()=>run(async create=>{const w=await create();const reply=await w.commandChannel.request('publish',{...publication(),context:{...w.info.commandContext,streamId:'ab'.repeat(32)}},new AbortController().signal);assert.equal(reply.code,'COMMAND_CONTEXT_MISMATCH');await w.stop();assert.equal(w.ended.journal.nonces,0)}));
test('restart-idempotency-keeps-one-event-with-new-host-incarnation',()=>run(async create=>{let w=await create();const first=await w.commands.publish(publication()),host=w.hello.hostId;await w.stop();w=await create();assert.notEqual(w.hello.hostId,host);assert.deepEqual(await w.commands.publish(publication()),first);await w.stop();assert.equal(w.ended.journal.nonces,1);assert.equal(w.ended.journal.events,1)}));
async function main(){if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));return}lib=await import(pathToFileURL(path.join(process.env.PAR_SDK_BUILD||path.join(ROOT,'product/wp10/lib'),'index.js')));const cases=[];for(const t of tests){try{await t.fn();cases.push({id:t.id,status:'PASS'});console.log('PASS',t.id)}catch(e){cases.push({id:t.id,status:'FAIL'});console.error('FAIL',t.id,e)}}if(process.env.HARNESS_RESULT_PATH)fs.writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));process.exitCode=cases.every(x=>x.status==='PASS')?0:1}
if(process.argv[1]&&path.resolve(process.argv[1])===new URL(import.meta.url).pathname)await main();
