import assert from 'node:assert/strict';import {Duplex} from 'node:stream';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const ROOT=process.env.PAR_ROOT||process.cwd(),tests=[];const test=(id,fn)=>tests.push({id:'event-command.channel.'+id,fn});let Channel;
const ctx={protocol:'par-local-event-commands-0040',appId:'test.app',spaceId:'11'.repeat(32),streamId:'22'.repeat(32),epoch:'1',schema:{body:'text'},schemaDigest:'33'.repeat(32),issuer:'44'.repeat(32),journalGeneration:'66'.repeat(32),authority:'owner-publish'};
const hello=()=>({v:1,kind:'hello',protocol:'par-local-event-commands-0040',hostId:'aa'.repeat(16),context:ctx,maxRequest:65536,maxResponse:1500000});
function frame(value){const raw=typeof value==='string'?Buffer.from(value):Buffer.from(JSON.stringify(value)),head=Buffer.alloc(4);head.writeUInt32BE(raw.length);return Buffer.concat([head,raw])}
class Peer extends Duplex{writes=[];_read(){} _write(b,e,cb){this.writes.push(Buffer.from(b));cb()}feed(x){this.push(frame(x))}}
function setup(){assert.equal(typeof Channel,'function','dedicated Node command channel is not implemented');const peer=new Peer();return {peer,channel:new Channel(peer,{expectedContext:ctx})}}
async function ready(){const x=setup();x.peer.feed(hello());await x.channel.ready;return x}
const sig=()=>new AbortController().signal;
test('dedicated-hello-incremental-frame',async()=>{const {peer,channel}=setup();try{for(const b of frame(hello()))peer.push(Buffer.from([b]));assert.equal((await channel.ready).context.authority,'owner-publish')}finally{await channel.close()}});
test('subscription-protocol-cannot-be-command-hello',async()=>{const {peer,channel}=setup();peer.feed({...hello(),protocol:'par-owner-event-host-0039'});await assert.rejects(channel.ready);await channel.close()});
test('authority-mismatch-closes-before-send',async()=>{const {peer,channel}=setup();peer.feed({...hello(),context:{...ctx,authority:'inquire-only'}});await assert.rejects(channel.ready);assert.equal(peer.writes.length,0);await channel.close()});
test('ack-not-in-command-operation-set',async()=>{const {peer,channel}=await ready();await assert.rejects(channel.request('ack',{},sig()),e=>e.code==='HOST_OPERATION_DENIED');assert.equal(peer.writes.length,0);await channel.close()});
test('canonical-publish-correlation',async()=>{const {peer,channel}=await ready();const pending=channel.request('publish',{operationId:'01'.repeat(16)},sig());const sent=JSON.parse(peer.writes[0].subarray(4));assert.equal(sent.op,'publish');assert.equal(sent.id,'1');peer.feed({v:1,id:'1',op:'publish',value:{marker:'receipt'}});assert.equal((await pending).marker,'receipt');await channel.close()});
test('abort-before-send-zero-writes',async()=>{const {peer,channel}=await ready();const ac=new AbortController();ac.abort();await assert.rejects(channel.request('publish',{},ac.signal));assert.equal(peer.writes.length,0);await channel.close()});
test('aborted-request-keeps-bounded-correlation',async()=>{const {peer,channel}=await ready();const ac=new AbortController();const p=channel.request('publish',{},ac.signal);ac.abort();await assert.rejects(p);assert.equal(channel.stats().inflight,1);peer.feed({v:1,id:'1',op:'publish',error:'HOST_REQUEST_CANCELLED'});await new Promise(r=>setImmediate(r));assert.equal(channel.stats().inflight,0);await channel.close()});
test('duplicate-json-keys-refused',async()=>{const {peer,channel}=setup();peer.feed('{"v":1,"v":1}');await assert.rejects(channel.ready);await channel.close()});
test('unknown-correlation-closes-channel',async()=>{const {peer,channel}=await ready();const p=channel.request('inquire',{},sig());peer.feed({v:1,id:'2',op:'inquire',value:{}});await assert.rejects(p);assert.equal(channel.stats().closed,true);await channel.close()});
test('bound-on-pending-direct-requests',async()=>{const {channel}=await ready();const a=channel.request('inquire',{},sig()).catch(()=>{}),b=channel.request('inquire',{},sig()).catch(()=>{});await assert.rejects(channel.request('inquire',{},sig()));assert.equal(channel.stats().inflight,2);await channel.close();await Promise.all([a,b])});
if(process.argv.includes('--list')){console.log(JSON.stringify(tests.map(t=>t.id).sort()));process.exit(0)}
try{Channel=(await import(pathToFileURL(path.join(ROOT,'product/wp10/node/command-channel.mjs')))).ConnectedCommandChannel}catch{}
const cases=[];for(const t of tests){try{await t.fn();cases.push({id:t.id,status:'PASS'});console.log('PASS',t.id)}catch(e){cases.push({id:t.id,status:'FAIL'});console.error('FAIL',t.id,e)}}
if(process.env.HARNESS_RESULT_PATH)fs.writeFileSync(process.env.HARNESS_RESULT_PATH,JSON.stringify({schema_version:1,nonce:process.env.HARNESS_NONCE||'standalone',cases}));process.exitCode=cases.every(x=>x.status==='PASS')?0:1;
